### ISSUE TITLE
doubles and around hook failure

### ISSUE THREAD

**Issue by apneadiving** [rspec/rspec-core#1598]
Hi,

The following raises `Failure/Error: double('test').as_null_object
       The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported.`

```
context "test" do
  around(:each) do |example|
    double('test').as_null_object
    example.run
  end

  it "foo" do
  end
end
```

Works with a `before` hook though.

**Comment by faucct** [comment]
An example of using doubles in an around would be stubbing something for the duration of example:

```ruby
around do |example|
  Container.stub('foo', double('bar'), &example)
end
```

Is there any reason for a public API `around` behaving different from `before` and `after`? I expect `before` and `after` to be particular cases of `around`, not something more powerful.

**Comment by faucct** [comment]
It looks like the default value for `scope` argument of `around` is not `:example`, but `:context`.

**Comment by JonRowe** [comment]
The default is `:example` it also supports `:context`, you have to call `example.run` it's not a block.

**Comment by faucct** [comment]
I have tried to say that it is really `around(:context)` despite it being called `around(:example)`.
You are right, it is not block. So here is an updated example:

```ruby
around do |example|
  Container.stub('foo', double('bar')) { example.run }
end
```

**Comment by myronmarston** [comment]
So, a few things:

> The default is `:example` it also supports `:context`

The default is `:example`, but it does _not_ support `:context`, as our docs say:

https://github.com/rspec/rspec-core/blob/v3.7.0/lib/rspec/core/hooks.rb#L313

That said, it looks like we don't properly warn or error on `:context` -- we really should.  When you define an `around(:context)` hook it really runs around each individual example.  You can confirm by looking at the output from this spec file:

``` ruby
RSpec.describe "Around" do
  around(:context) do |ex|
    puts "around before"
    ex.run
    puts "around after"
  end

  it 'works' do
    puts "in example 1"
  end

  it 'works again' do
    puts "in example 2"
  end
end
```

```
Around
around before
in example 1
around after
  works
around before
in example 2
around after
  works again
```

> you have to call example.run it's not a block.

While the arg passed to the `around` block is not a block, it defines a `to_proc` so you can treat it as one when passing it to a transactional method:

``` ruby
  around(:context) do |ex|
    DB.transaction(rollback: :always, &ex)
  end
```

See also: https://github.com/rspec/rspec-core/blob/v3.7.0/lib/rspec/core/example.rb#L339-L350

With all that out of the way, let's get back to @faucct's example:

``` ruby
around do |example|
  Container.stub('foo', double('bar')) { example.run }
end
```

When you pass a block to `stub`, you are defining an implementation for the stub method.  In other words, your block is passed when the stubbed method is called.

So in this case, you are stubbing `Container.foo` so that when `Container.foo` is called, the example gets run.

It sounds like you're expecting the block passed to stub to define the scope in which the stub is available, but that's not how rspec-mocks works.  The way to define a scope in which rspec-mocks constructs are available is `RSpec::Mocks.with_temporary_scope`:

``` ruby
RSpec::Mocks.with_temporary_scope do
  # you can define any mocks/stubs/doubles in here, and they will be
  # rolled back at the end of the block
end
```

However, RSpec essentially wraps every example in this kind of scope to begin with.  All rspec-mocks features are automatically scoped to individual examples, with no need for any configuration on your part.

@faucct what are you trying to accomplish that's not working without trying to use an `around` hook for this?

**Comment by faucct** [comment]
You misunderstood what I am trying to achieve in my example. `Container.stub('foo', double('bar'), &example)` should make `Container.foo` return `double('bar')` for the duration of block - `example`.
The problem is that doubles aren't available inside `around(:example)`, as the docs [say](https://relishapp.com/rspec/rspec-core/v/3-0/docs/hooks/around-hooks). Does it have any reason behind?

**Comment by myronmarston** [comment]
> You misunderstood what I am trying to achieve in my example. `Container.stub('foo', double('bar'), &example)` should make `Container.foo` return `double('bar')` for the duration of block - `example`.

No, I understood what you are trying to achieve, but passing a block to the RSpec's `stub` method does not define the duration for when the stub is available.  If you stub a method in an example or a `before` hook, RSpec will automatically make it only available for the duration of the example, with no work needed on your part to do anything.

That said, are you trying to use minitest-mocks?  I understand it provides a `stub` method that works differently (and I think it may work in the way you describe), but if you're using it, you're on your own for integrating it with RSpec.

> Does it have any reason behind?

The reason is that RSpec is already defining the scope for you, by setting up mocks before `before` hooks run, and tearing them down after `after` hooks are run.  `around` hooks are implemented in a way that wraps the entirety of every example (including the hooks and the mocks setup/teardown).

It _might_ be possible to refactor to enable rspec-mocks to be used in `around` hooks but if we're going to spend time on that we want to see a use case for why the mocks have to be setup in an `around` hook and not in a `before` hook or the example itself.

**Comment by faucct** [comment]
I was talking about [`Dry::Container#stub`](http://dry-rb.org/gems/dry-container/testing/) method. It behaves the way I described it and it would be laconic to use it in `around` method, not in `before` and `after`:

```ruby
around do |example|
  Container.stub(:foo, double('bar'), &example)
end

# or

before do
  Container.stub(:foo, double('bar'))
end
after do
  Container.unstub(:foo)
end
```

**Comment by myronmarston** [comment]
OK, then you're not talking about the rspec-mocks `stub` method.  In that case, if `Dry::Container#stub` supports a block, what you're trying should "just work", and I don't see any reason for it not to.  Have you tried it?  If it doesn't work, what kind of error do you get?

**Comment by faucct** [comment]
The docs say you should not be able to use doubled inside around calls.

**Comment by myronmarston** [comment]
> The docs say you should not be able to use doubled inside around calls.

The docs are referring to **RSpec's** doubles--e.g. doubles created by APIs provided by rspec-mocks, or more specifically, doubles created by whatever mocking library you have configured via `config.mock_with` (which defaults to RSpec).

`Dry::Container` isn't a full mocking library, and (presumably) you haven't configured RSpec to `mock_with Dry::Container`.  It looks like `Dry::Container` defines simple API for stubbing/unstubbing that isn't integrated into any test framework, and should be usable anywhere without restriction.

Again, have you tried to do what you want to do?  If it gets an error that points to a problem caused by RSpec we can take a look.

**Comment by faucct** [comment]
`double` is an RSpec double. The `dry-container` method I use is `Container.stub`.

**Comment by myronmarston** [comment]
OK, then you can define an extra rspec-mock scope for your `around` hook:

``` ruby
around do |example|
  RSpec::Mocks.with_temporary_scope do
    Container.stub(:foo, double('bar'), &example)
  end
end
```

Or use something besides `double` as replacement for the `foo` here.
