### ISSUE TITLE
`lets` block for defining multiple let blocks at once

### ISSUE THREAD

**Issue by JoshCheek** [rspec/rspec-core#1650]
**The code is [here](https://gist.github.com/JoshCheek/09f01dcced9bea02360d).**

---

I had a method that returned three values (stdout, stderr, exit status), and setting these values with let blocks was quite obnoxious:

``` ruby
let(:results) { call "args" }
let(:stdout)  { results[0] }
let(:stderr)  { results[1] }
let(:status ) { results[2] }
```

So I wound up using local variables, because then I could just do:

``` ruby
stdout, stderr, status = call "args"
```

This had drawbacks, though:
- If it blew up, it did it at definition time rather than test time, so feedback about where/why was poor (rather than this test failing, it just exited Ruby)
- It kept sharing variables across contexts, so by the time the test got to running, the value of the variable had changed (yeesh, that's annoying!)

So I decided I'd like to be able to have a `lets` block, which is the same as a `let` block, except it sets multiple names at once so that it works more like the local variable example. Now I can do:

``` ruby
lets(:stdout, :stderr, :status) { call "args" }
```

Figured I'd post it here, and see if it fit with what y'all are trying to do, before trying for a PR.

**Comment by skatenerd** [comment]
I personally ran into this issue when trying to refactor away from `let` statements and towards explicitly invoking helper methods to set up my data.  Specifically, I was addressing this pattern:
```
describe 'foo' do
  let(:age) {100}
  let(:panelist) { Panelist.create!(age: age) }
  let(:analyzer) { Analyzer.new(panelist) }
  describe 'bar' do
    let(:age) {300}
    it "is very old" do
        expect(analyzer.get_panelist_age()).to eql(300)
        expect(analyzer.get_panelist_age()).to eql(panelist.age)
    end
  end
end
```

I thought this was really tricky/fragile, as it relied on laziness, and because I couldn't understand the test itself without looking at all of the "parent" specs and simulating in my brain how all of the different setup code would interact.  So, I thought to myself, I know how to make things explicit: using arguments.  I created a helper method which accepts an 'age' argument and returns the `analyzer` and the `panelist`.  That's when I started googling and found this issue.

The approach I took was to just write code like:
```
it "foo" do
  analyzer, panelist = setup(300)
  ...
end
```

The main frustration I have is that, if I have _more_ setup code, and the setup code requires access to `analyzer` and `panelist`, then that setup code can't use `let`!  Once I've gone down the path of splat-into-local-variables-by-hand, suddenly `let` is totally off limits and I get a lot of repetition in my tests.

As for the semantics of how you would implement this, I feel like you would want `call "args"` to return a hash.  After that point, you can't go wrong with crashing often and early.  If the user-provided variable names (on the left-hand-side) don't align with the keys of the returned hash, then the test is invalid.

**Comment by skatenerd** [comment]
I personally ran into this issue when trying to refactor away from `let` statements and towards explicitly invoking helper methods to set up my data.  Specifically, I was addressing this pattern:

```
describe 'foo' do
  let(:age) {100}
  let(:user) { User.create!(age: age) }
  let(:analyzer) { Analyzer.new(user) }
  describe 'bar' do
    let(:age) {300}
    it "is very old" do
        expect(analyzer.get_user_age()).to eql(300)
        expect(analyzer.get_user_age()).to eql(user.age)
    end
  end
end
```

I thought this was really tricky/fragile, as it relied on laziness, and because I couldn't understand the test itself without looking at all of the "parent" specs and simulating in my brain how all of the different setup code would interact.  So, I thought to myself, I know how to make things explicit: using arguments.  I created a helper method which accepts an 'age' argument and returns the `analyzer` and the `user`.  That's when I started googling and found this issue.

The approach I took was to just write code like:
```
it "foo" do
  analyzer, user = setup(300)
  ...
end
```

The main frustration I have is that, if I have _more_ setup code, and the setup code requires access to `analyzer` and `user`, then that setup code can't use `let`!  Once I've gone down the path of splat-into-local-variables-by-hand, suddenly `let` is totally off limits and I get a lot of repetition in my tests.

As for the semantics of how you would implement this, I feel like you would want `call "args"` to return a hash.  After that point, you can't go wrong with crashing often and early.  If the user-provided variable names (on the left-hand-side) don't align with the keys of the returned hash, then the test is invalid.
