### ISSUE TITLE
Still got problems with pattern in 3.1.5

### ISSUE THREAD

**Issue by gavinheavyside** [rspec/rspec-core#1728]
I'm seeing problems with file globs and the pattern option in 3.1.5 (OS X Mavericks, Ruby 2.1.3). I've got acceptance specs in `acceptance`, and an `:acceptance` task

``` ruby
RSpec::Core::RakeTask.new(:acceptance) do |t|
  t.rspec_opts = %w[--color]
  t.pattern = "acceptance/**/*_spec.rb"
end
```

This is generating the command 

```
➜  project git:(tidy-up-gems) ✗ rake acceptance
/path/to/rspec-core-3.1.5/exe/rspec --pattern acceptance/\*\*/\*_spec.rb --color
No examples found.
```

There are plenty of specs matching the `acceptance/**/*_spec.rb` file glob, and the otherwise identical task for `spec/**/*_spec.rb` seems to work fine.

**Comment by tmertens** [comment]
@myronmarston has this regressed?  I have the same problem as originally stated in this defect, and have tried rspec-core 3.2.3, 3.2.0, and 3.1.7 to no avail.

Given there are tests in another top level directory besides `rspec` (e.g. `regression_tests`), the following command:

```
bundle exec rspec --exclude-pattern "**/acceptance/**/*_spec.rb" --pattern "**/*_spec.rb"
```

will only run the tests in the `spec` directory.

**Comment by myronmarston** [comment]
@tmertens -- I believe your problem is the `--default-path` option:

https://relishapp.com/rspec/rspec-core/v/3-2/docs/configuration/setting-the-default-spec-path

Since you haven't passed a path to `rspec` the default `--default-path` is used, which means that your command is equivalent to:

```
bundle exec rspec spec --exclude-pattern "**/acceptance/**/*_spec.rb" --pattern "**/*_spec.rb"
```

...which runs only the tests in the `spec` directory, naturally.  The solution is to always pass a path at the command line:

```
bundle exec rspec . --exclude-pattern "**/acceptance/**/*_spec.rb" --pattern "**/*_spec.rb"
```

...or add an option to `.rspec`:

```
--default-path .
```

That should fix the problem for you.  Note that using `.` as the default path may have the unintended side effect of running specs from the libraries you use, if they get installed in a subdirectory of the project root (which is what `bundle install --standalone --binstubs` would do).  Is there any reason you don't want to move the `regression_tests` directory into `spec`?

**Comment by tmertens** [comment]
Thanks @myronmarston that resolved it.

For anyone else looking at this, I also had to make the following changes, because `spec` no longer gets automatically added to the load path:

In `.rspec`:
```
--require spec/spec_helper
```

In `spec/spec_helper.rb`:
```ruby
$:.unshift File.dirname(__FILE__)
```

**Comment by tmertens** [comment]
Oh also:

>  Is there any reason you don't want to move the regression_tests directory into spec?

The short answer to your question is 'yes'.

**Comment by myronmarston** [comment]
> For anyone else looking at this, I also had to make the following changes, because spec no longer gets automatically added to the load path:

You can also pass `-I` to set up the load path.  For example, your `.rspec` could have:

```
--default-path .
-I spec
--require spec_helper
```

...with no need to mess with `$:.unshift`.
