### ISSUE TITLE
RSpec executes examples in the order not as they're defined

### ISSUE THREAD

**Issue by andrewpanin** [rspec/rspec-core#1756]
I posted this question on StackOverflow: http://stackoverflow.com/questions/26653244/why-rspec-runs-examples-in-the-order-not-as-theyre-declared

In brief, even though the documentation tells that by default, examples are executed in the order as they're defined, in fact they're not. Or that documentation looks a bit misleading.

**Comment by IamNaN** [comment]
I just updated my gems and the order is no longer working the way I expected. It feels sort of broken. I like to write my tests before the code. The first test should be the first to fail. I write the code to make that work, it passes, the next test fails, and so on. You know the drill.

Unless you write your spec with a really restrictive and flat notion of contexts, the first to fail could be any test in the spec file. I'm using capybara, so I'll use `features` and `scenarios` in this example:

    feature 'Comments' do
      background do
        # create something to put comments on
      end

      feature 'can be created' do
        scenario 'by the original author' do
          ...
        end
  
        scenario 'by moderators' do
          ...
        end
  
        scenario 'by other users' do
          ...
        end
      end
  
      scenario 'can be viewed' do
        ...
      end
    end

This might not be the best example, but it does clearly shows how rspec present the developer with a chicken-and-egg problem: it jumps to the `viewing` scenario before any of the `create` scenarios. I think technically, this is correctly written spec but it can't be used for TDD. From a rubist's perspective evaluating specs top-down and then recursively when a nested context is encountered is clearly most expected. It doesn't appear that's possible currently.

I totally accept that I might be missing some key point.

**Comment by JonRowe** [comment]
As above if you put the bottom scenario in a context it will work the way you expect.

**Comment by myronmarston** [comment]
The ordering you're seeing is the ordering that RSpec has always used, AFAIK.  I wasn't around in the early days so it may have changed between RSpec 1 and 2, but I'm fairly sure that the current ordering (except when you run specs with `--order random`) is the same as it was in RSpec 2.  @IamNaN, you mention that it stopped working how you expect after upgrading RSpec...can you tell us what version you were running before that worked differently?

**Comment by IamNaN** [comment]
@myronmarston I jumped a major and then some from 2.14 to 3.1. It's entirely possible I haven't encountered this problem until now, by accident.

What @JonRowe suggests would work, but I'm afraid it would become troublesome to manage over time.

Instead, maybe I need to stop using contexts, at least like this. Divvy up the behavior into different files. In the example, there would be a file for creating and another for viewing comments. The trade-off is DRY-ness (especially with regards to backgrounds) and remembering to run the dependent specs. Clarity/predictability is a win, so it seems worth it.

**Comment by myronmarston** [comment]
> @myronmarston I jumped a major and then some from 2.14 to 3.1. It's entirely possible I haven't encountered this problem until now, by accident.

I put together an example project that's getting the same ordering in 2.14 and 3.1:

https://gist.github.com/myronmarston/c0fa28496034730ad363

Can you `git checkout <old SHA>` on one of your projects when it was on 2.14 to see if it produces the same ordering?

Anyhow, I'm open to changing the way the defined ordering works, but I've been skeptical that it's much of a real problem for users given that I didn't think it had ever changed and this issue (opened a couple months ago, after RSpec was ~9 years old) is the first I'd heard any user feedback about the ordering.  Your feedback is useful as another datapoint that an RSpec user is disliking how the ordering works.  We may address this in a future release if there is more widespread community demand.

**Comment by IamNaN** [comment]
I appreciate you looking into that... Browsing the old specs in the history I can see they are a lot more simple. The projects I've been working on have become more complicated and the tests more sophisticated so I'm exercising *all* my tools more. The project I'm on now is probably my largest in a few years and missed this issue by happenstance until today (which coincided with a gem update, so there was some synchronicity involved here). I have to wonder how many other people are sidestepping it "just because".

All else being equal, I'm really glad to have rspec in my toolkit. It's saved me untold hours and is generally a pleasure to work with. So thanks for that.

**Comment by fgarcia** [comment]
Should I assume that examples and contexts will never be at the same nesting level?

Until now I always considered :random order a mandatory option that promotes sane isolated tests

However in a project where I must restart multiple services with asynchronous expectations for a few tests, a full tear up/down for each example is very expensive. Only in this case I found very tempting having groups and examples at the same nested level, mostly to document with detail each step of the few long-integration process

**Comment by myronmarston** [comment]
For a slow integration test I'd recommend using `aggregate_failures` so that you can perform the slow setup/teardown only once but make many expectations and still see all failures:

https://relishapp.com/rspec/rspec-core/v/3-4/docs/expectation-framework-integration/aggregating-failures

**Comment by mib32** [comment]
Sorry, but why when i run tests like that
```
rspec --format d --order defined spec/features/owner/users_spec.rb spec/libs/merchant_importers_spec.rb spec/features/authorization/sign_up_spec.rb
```

they run in the order 3, 1, 2 (where number is the corresponding number of argument in command line call)

**Comment by myronmarston** [comment]
Because RSpec loads the spec files in alphabetical order, not in the passed order, and "spec/libs/merchant_importers_spec.rb" < "spec/features/owner/users_spec.rb" < "spec/features/authorization/sign_up_spec.rb".  See #660 for the background on this.  `--order defined` makes the specs run in the order they are defined, and they get defined as the spec files are loaded, so the the file load order determines the run order.

If you want things to run in a specific order, we provide an API to do that:

* http://rspec.info/documentation/3.4/rspec-core/RSpec/Core/Configuration.html#register_ordering-instance_method
* https://relishapp.com/rspec/rspec-core/v/3-4/docs/configuration/overriding-global-ordering
