### ISSUE TITLE
Provide a way to output data from example to formatter

### ISSUE THREAD

**Issue by abotalov** [rspec/rspec-core#1851]
I'd like to send some data from my test (i.e. example) to formatter (custom formatter).

I'd like formatter to handle at least simple strings and screenshots (like `puts` and `embed` in Cucumber's RbWorld).

I haven't found a way to send data from example to formatter at all (Formatters API has a `message` method but I haven't found way to use that `message` in examples). It would be good if the usage of API would be as easy as in Cucumber. I believe it would be even better to allow formatter to handle objects of any types (for example user can write `output(SomeClass.new)` in example, and then reporter will send the instance to formatter. Formatter itself will be able to decide how it wants to handle it).

Related:
http://stackoverflow.com/questions/16539945/rspec-html-report-with-fail-screenshot

**Comment by JonRowe** [comment]
At the moment you'd have to use `RSpec.configuration.reporter.message(thing_you_want_to_send)`, which would support anything you'd wish to send your formatter but wouldn't be within the structure of the notification cycle.

**Comment by nyarly** [comment]
At the moment, Reporter#message, Reporter#notify et al are marked `@private` - if that's a solid recommendation, can we get some of the Reporter notification messages to be made public?

**Comment by nyarly** [comment]
Looking deeper at this, could the reporter be made available in the ExampleGroup instance? Using the Rspec.configuration.reporter rather than the argument to example.run seems brittle.

**Comment by myronmarston** [comment]
> At the moment, Reporter#message, Reporter#notify et al are marked @private - if that's a solid recommendation, can we get some of the Reporter notification messages to be made public?

In general, if there's a private API that fills a need that someone needs, we're willing to make it public and/or add new public APIs...but I'll let @JonRowe answer for this specific case as he's the resident formatter/reporter expert :).

> Looking deeper at this, could the reporter be made available in the ExampleGroup instance? Using the Rspec.configuration.reporter rather than the argument to example.run seems brittle.

Sure, you can make it available yourself using a module:

``` ruby
module ReporterAccessor
  def reporter
    RSpec.configuration.reporter
  end
end

RSpec.configuration.include ReporterAccessor
```

I'd prefer that RSpec not ship with that method because the example group scope is primarily reserved for users to define their own helper methods.  In RSpec 2, we had an `example` method and some users hit cases where they had defined their own `example` method without realizing the conflict, so we switched in RSpec 3 to yielding the example.  Likewise, if we shipped with a `reporter` method, it could conflict with a helper method defined by the user named `reporter`.

**Comment by nyarly** [comment]
My concern is that RSpec.configuration.reporter isn't guaranteed to be the same reporter that e.g. examples use to register their start and results with. If it is, bene, but if so, why does a reporter argument get threaded through ExampleGroup::run_examples *et al?*

I'm not clear on the mechanics, but I'm worried for instance about the existence of the NullReporter - if an EG is being run with a NullReporter and I say `RSpec.configuration.reporter.notify :message, message` then those messages get sent to formatters anyway. There's also the possibility that the reporter changes and I'm then notifying the wrong set of formatters.

**Comment by myronmarston** [comment]
The reporter argument (and the `NullReporter`) are there to facilitate testing.  It allows us to define and run example groups from within individual examples for when we are testing RSpec itself or when 3rd party extensions want to use a similar technique (perhaps with the new [sandboxing API](http://rspec.info/blog/2015/02/rspec-3-2-has-been-released/#core-new-sandboxing-api) released in 3.2 today).  See, for example, [this spec](https://github.com/rspec/rspec-core/blob/67f933c444d4b3b17bc9bed85de280ef4bc40983/spec/rspec/core/memoized_helpers_spec.rb#L68-L83) -- within the spec we define an example group and run it in order to test how `subject` works.  When doing this, we specifically don't want the internally-defined example group to report its status to the normal reporter, as the output of running rspec-core's spec suite would get very jumbled if the example groups defined within individual specs all reported their status to stdout.  Thus we use the `NullReporter` in that case and it's the default argument value because we use that technique in so many places.

However, that really only comes in play when someone explicitly calls `run` on an example group.  The RSpec runner itself always passes `RSpec.configuration.runner`, so that reporter will always get used in all normal spec suites.

**Comment by JonRowe** [comment]
> In general, if there's a private API that fills a need that someone needs, we're willing to make it public and/or add new public APIs...but I'll let @JonRowe answer for this specific case as he's the resident formatter/reporter expert :).

I think we can add an API here to send message with arbitrary data, it pretty much fits what we need here, I'm loathe to make the existing method public as is, (as it would be unbalanced with the rest and I don't want to support a custom lifecycle at this point) and would rather add a pass through somewhere instead.

> My concern is that RSpec.configuration.reporter isn't guaranteed to be the same reporter that e.g. examples use to register their start and results with. If it is, bene, but if so, why does a reporter argument get threaded through ExampleGroup::run_examples et al?

It's supposed to be guarenteed to be the same, if it isn't something has gone wrong somewhere...

**Comment by nyarly** [comment]
So: there's *definitely* a case where the argument and the configured runner are different: in sandboxing. I see the logic of not wanting to pollute the ExampleGroup instance - could it be a field on the example object then? As I'm developing this plugin, I'm at least one client of RSpec who'd like to make sure there was control over which runner is receiving my messages.

**Comment by nyarly** [comment]
@JoneRowe - in terms of balance and lifecycle: does that matter? I'm intending to use notify directly, which would (almost) guarantee that my formatters are the only ones who'll receive my messages. That makes it a "buys your ticket, takes your chances" kind of a deal, right? Am I missing something about the reporter/formatter component?

**Comment by myronmarston** [comment]
> So: there's definitely a case where the argument and the configured runner are different: in sandboxing. I see the logic of not wanting to pollute the ExampleGroup instance - could it be a field on the example object then? As I'm developing this plugin, I'm at least one client of RSpec who'd like to make sure there was control over which runner is receiving my messages.

Yes, I think adding an attribute to `RSpec::Core::Example` would make sense.  Then you could do:

``` ruby
it "does stuff" do |ex|
  ex.reporter.do_whatever
end
```

**Comment by JonRowe** [comment]
So I've worked up a PR to expose the reporter, and after thinking about it I am just going to make `#message` a publicly supported API, unlike the other notifications it's not part of the lifecycle so I think thats ok.

**Comment by nyarly** [comment]
@JonRowe Can I actually plead for #notify ? The named events/registry thing is really flexible, but having to filter :message events intended for other formatters seems like re-inventing that each time.

**Comment by JonRowe** [comment]
I'm not sure what you're asking for? 

`#notify` is part of the internal workings of the formatter, I don't want to support people sending *any* of the notifications because it would be trivial to break the lifecycle of the reporter in that way.

There is currently no way to pick a specific formatter to talk to...

**Comment by myronmarston** [comment]
Correct me if I'm wrong, but from what you've said, it sounds like you want to send a custom notification to a custom formatter.  If that's the case, and you control both the formatter and the notification origination site, I recommend you cut RSpec out entirely and just do it yourself with something like:

``` ruby
class MyCustomFormatter
  def self.instances
    @instances ||= []
  end

  def initialize(*args)
    # do normal stuff
    self.class.instances << self
  end

  def self.my_custom_event(notification_object)
    instances.each { |i| i.my_custom_event(notification_object) }
  end
end

# from somewhere else
MyCustomFormatter.my_custom_event(notification_object)
```

**Comment by nyarly** [comment]
Something like that - the feature I have in mind would need the event listeners (since we're no now longer talking about reporter/formatter notifications) to be of different classes, likely different libraries - but at the same time at least some of them would be Formatters as well.

The problem I'm having is that even if I do build a different event dispatcher, I need to coordinate with RSpec events, which leads to a coupling of the sequence of the events - which is fine so long as e.g. RSpec remains entirely single threaded, I think.

I can see why you'd want to avoid client code sending :start or :seed, but restricting clients to :message events seems needlessly complex. I'll grant, the solutions I see to preventing access to lifecycle event names are complex as well, but it'd be encapsulated within the Reporter, rather than spread across Formatters.
