### ISSUE TITLE
Order of profiles/summary/rerun

### ISSUE THREAD

**Issue by maxlinc** [rspec/rspec-core#1856]
The current version of rspec prints the summary, rerun commands and then the profile. I find the profile information useful but I only occasionally look at it. I *always* want to see the summary/rerun commands immediately after the tests finish. So I find it annoying having to scroll up to see the summary.

It appears that RSpec's original order matched my preferences and that the change was introduced in [#1515](https://github.com/rspec/rspec-core/pull/1515). You can clearly see the order before that PR was profile, summary line, then rerun commands:

```ruby
def dump_summary(summary)
  dump_profile unless mute_profile_output?(summary.failure_count)
  output.puts "\nFinished in #{summary.formatted_duration}" +
  " (files took #{summary.formatted_load_time} to load)\n"
  output.puts summary.colorize_with ConsoleCodes
  dump_commands_to_rerun_failed_examples
end
```

However, the PR changed it so the dump_profile happens after dumping the summary:
```ruby
# @method dump_profile
# @api public
#
# This method is invoked after the dumping the summary if profiling is
# enabled.
```

Would you consider changing it back to the original order or adding an option to swap the order?

**Comment by myronmarston** [comment]
Thanks for reporting this!  I didn't realize we had changed the order of things here...when I reviewed #1515 I didn't notice that.  My guess is that it wasn't an intentional change on @JonRowe's part.  @JonRowe, can you confirm or deny?

Regardless, I just looked at the output from 2.x compared to 3.x when `--profile` has been passed, and I agree that the 2.x output is ordered better.  I think that I'd like to swap the order (no option needed) unless someone makes a specific case for the order it is in now.

**Comment by JonRowe** [comment]
No objection, I'd guess I thought it'd be logical to have it after the summary but it wasn't an intentional change.

**Comment by myronmarston** [comment]
@maxlinc, do you want to take a stab at this? Otherwise I may try to get to it...but I always like getting contributions from the community :).
