### ISSUE TITLE
Regression on ruby 1.8.7 in rspec-core 3.2.0

### ISSUE THREAD

**Issue by cmurphy** [rspec/rspec-core#1864]
We're seeing an issue on ruby 1.8.7 when trying to require rspec. The traceback is

```
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:512:in `all_hooks_for': return from proc-closure (LocalJumpError)
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:564:in `process'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/flat_map.rb:11:in `map'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/flat_map.rb:11:in `flat_map'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:563:in `process'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:429:in `register_globals'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:394:in `set_it_up'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:361:in `subclass'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:253:in `describe'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:43:in `__send__'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:43:in `describe'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:82:in `__send__'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:82:in `describe'
	from /home/travis/build/puppetlabs/puppetlabs-apt/spec/classes/apt_spec.rb:2
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.0/exe/rspec:4
```

You can see the whole test environment here: https://travis-ci.org/puppetlabs/puppetlabs-apt/jobs/49343840

Since https://rubygems.org/gems/rspec-core still claims support for ruby 1.8.7 this seems like a regression to us.

Happy to provide any other info I can.

**Comment by myronmarston** [comment]
Thanks for reporting this.  RSpec 3 does still support 1.8.7, and in fact our travis builds are all green on 1.8.7.  There must be a case that your environment, configuration or specs hit that our test cases don't.  I'll have to dig into it to see what's causing that.

To repro, do I just clone https://github.com/puppetlabs/puppetlabs-apt, `bundle install` and `bundle exec rspec` on 1.8.7?  Or is there more to it than that?

**Comment by cmurphy** [comment]
We've pinned rspec-core to 3.1.7, so you'll have to check out e8bef852edb3451d07fb3ff7f865aa7329a25c42 to see the issue.

Thanks!

**Comment by myronmarston** [comment]
So it appears that the problem is Puppet's `Symbol#to_proc` monkey patch:

https://github.com/puppetlabs/puppet/blob/3.7.4/lib/puppet/util/monkey_patches.rb#L80-L83

...which explains why I never saw this failure on 1.8.7 before.  I've put together a gist demonstrating that the presence of that monkey patch causes this failure:

https://gist.github.com/myronmarston/75d5b470a8d258ed7f04

Clone that, and on 1.8.7, run `bundle exec example_spec.rb` and compare that to `MONKEYPATCH_SYMBOL=1 bundle exec rspec example_spec.rb` -- you'll see that the `LocalJumpError` only happens when your `Symbol#to_proc` monkey patch is loaded.

It's not clear to me why your monkey patch causes this error, but regardless, when you monkey patch a core ruby method like `Symbol#to_proc`, and it breaks things, your own your own.  We can't support you.

I noticed that that monkey patch was removed in puppetlabs/puppet@65ca17c48abc8acb23a1b552e0ca371eddcebae2, so maybe you can upgrade to a newer puppet to avoid the error?

**Comment by cmurphy** [comment]
Thanks so much for looking into this. We're planning to drop support for that version of puppet soon, so we'll just pin until then. Thanks!
