### ISSUE TITLE
Option to suppress `Run options: include {:focus=>true}`

### ISSUE THREAD

**Issue by LandonSchropp** [rspec/rspec-core#1896]
It would be great to be able to suppress this message, especially when none of the specs are currently being filtered out. There's a [StackOverflow post](http://stackoverflow.com/questions/27698184/how-to-suppress-rspec-run-options-include-focus-true) addressing this topic.

**Comment by myronmarston** [comment]
You can always remove the `filter_run :focus` line if you don't find spec filtering useful.  For people who do find spec filtering useful, I think it's important that we emit output indicating what filtering is in effect...otherwise it's hard to understand why RSpec skipped some examples.

As mentioned in the Stack Overflow issue, RSpec already supports a very flexible system for deciding what output you want and what output you don't want in the form of the formatter system.  We don't want to add the extra complexity and maintenance burden of an alternate system of configuring the output via suppression flags.  If we added one suppression flag, I expect users would start asking for others, which would take our time away from other more important features.

You can also use `grep` for this:

```
rspec | grep -v "Run options"
```

**Comment by LandonSchropp** [comment]
Thanks for the reply! I *like* being able to filter tests. It's really handy for being able to focus on one failure without worrying about all the others. However, I probably only use this feature once a week or so. The other 99% of the time, it's annoying to see this message over and over. I understand it's important to output messaging when a filter is in affect, but when one isn't being applied then the message is annoying. If not a suppression flag, it would be nice if hiding the message on no filter were the default.

Just my 2¢.

**Comment by myronmarston** [comment]
It's something we would consider if many RSpec users expressed a desire for this change, but as far as I know, you are the only user who has ever requested this.  You can just implement your own formatter to get the output you want in the meantime.

**Comment by draffensperger** [comment]
@myronmarston thanks for all your hard work on RSpec! It's awesome :)

I would like this feature as well (and the referenced stack overflow question has 8 upvotes and 142 views so it seems that at least some other people would like it too).

I just created a pull request for it: https://github.com/rspec/rspec-core/pull/2007

**Comment by LandonSchropp** [comment]
I'd also like to add that now that I'm using the excellent [parallel_specs](https://github.com/grosser/parallel_tests) gem, I see this message eight times instead of just once.

**Comment by draffensperger** [comment]
One other note: I thought about trying to do this in a formatter, but my understanding of the code is that this message is shown in `world.rb` and would be called before the formatters are engaged (though please correct me if I'm wrong on that).
