### ISSUE TITLE
Rspec  to execute different spec files in desired order

### ISSUE THREAD

**Issue by chandanaGollapudi** [rspec/rspec-core#1900]
Hi ,

I have recently started using ruby and rspec. I am facing some issue in executing different spec files in desired order. rather executing tests in specified order,  tests execution is in alphabetical order . But I would like to execute tests in the order provided user.

Initially i tried using rake,but going through several post came to know the best way to this through rpsec and there are several options to do that and rspec won't  consider order that has given in CLI .

Could someone help me to sort out  this in best way and pls elaborate on implementing it?

**Comment by myronmarston** [comment]
> am facing some issue in executing different spec files in desired order. rather executing tests in specified order, tests execution is in alphabetical order .

RSpec does not execute tests in alphabetical order.  It loads spec files in alphabetical order and then runs tests in defined order or random order depending on your configuration.

In general, we recommend you use random ordering as that helps surface ordering dependencies, which can help you fix them when they first surface.

If you want move control over the ordering, you can use `config.register_ordering`:

http://rspec.info/documentation/3.2/rspec-core/RSpec/Core/Configuration.html#register_ordering-instance_method

If you want more info about how to use that option, see this recent discussion on the mailing list:

https://groups.google.com/forum/#!topic/rspec/mCCXj8RROYc

**Comment by myronmarston** [comment]
Closing as there's nothing actionable for us to do here.  But I'm happy to continue the conversation if you have followup questions, @chandanaGollapudi.

**Comment by chandanaGollapudi** [comment]
thanks your quick response( to request no 1900).I have gone through link that you suggested.i have few clarifications on below provided code.
Could you please provide your answers on below points.

1.In which file i need to add below provided code( is it spec_helper.rb or new spec file)?
1.1 if it is spec_helper,now different scrum team using same spec_helper file. will it affect others execution,if so how to handle it?

1.2 can archive same by creating new spec file and add below code to that.will it execute all other spec files in desired order by running new spec?

2.what is the significance of numerics in below code? as per my understanding groups execution order will be based on tags and the order will be feature,request and model.

lets say i have 3 test under each spec file . can the below code support in executing test in written order ? if not, could tell me how to that?

Could you point me to the link that gives detailed info about rspec for beginners?

RSpec.configure do |config|
config.register_ordering(:global) do |items|
items.sort_by do |group|
case group.metadata[:type]
when :feature then 50
when :request then 40
when :model then 10
else 20
end
end
end
end

thanks in advance,
Chandana

**Comment by myronmarston** [comment]
> 1.In which file i need to add below provided code( is it spec_helper.rb or new spec file)?

If you want it to always apply to every spec run, add it to a file that it always loaded.  `spec_helper.rb` is a pretty conventional place to put code you want always loaded for every spec run (or in a file required from `spec_helper.rb`).

> 1.1 if it is spec_helper,now different scrum team using same spec_helper file. will it affect others execution,if so how to handle it?

It seems like a bad idea to force a different ordering than other devs or teams use on the project (it could hide ordering dependencies that one team sees but not the other).

If you want to just apply the ordering for when you run `rspec`, you can add the ordering code to some file (e.g. `spec/support/change_global_ordering.rb`) and then add a git-ignored `.rspec-local` file to the project with `--require support/change_global_ordering` as the contents.  `.rspec` and `.rspec-local` can contain CLI flags you always want to apply (the former being intended to be project-wide for all devs, while the latter being for personal preferences).  `--require` will load the specified file so you can use it to load your ordering logic.

> 1.2 can archive same by creating new spec file and add below code to that.will it execute all other spec files in desired order by running new spec?

I don't understand this question.

> 2.what is the significance of numerics in below code? as per my understanding groups execution order will be based on tags and the order will be feature,request and model.

The absolute numeric values don't actually matter -- it's just how they sort relative to each other.  `sort_by` sorts low to high, so that code orders model specs first, feature specs last, request specs 2nd-to-last, and everything else in between model and request specs.

> lets say i have 3 test under each spec file . can the below code support in executing test in written order ? if not, could tell me how to that?

You can write the ordering logic to order the specs however you like.  We chose a block-based API because it supports _any arbitrary logic_ a user could want.  Just put ruby code in there that sorts the list however you want it to sort it.  I don't have the time to write the code for you (sorry).

Honestly, changing the ordering is a more "advanced" feature of RSpec and not something I generally recommend unless you have needs that are outside the norm and you know what you're doing.  I generally recommend running specs in random order  (`--order random`) which helps surface ordering dependencies so you can quickly solve them when they arise.  Using the ordering API to force an ordering to work around some issue is going to cause other problems for you in the long term.

> Could you point me to the link that gives detailed info about rspec for beginners?

* https://skillsmatter.com/skillscasts/5438-welcome-back-to-rspec
* https://pragprog.com/book/nrtest2/rails-4-test-prescriptions
* http://www.pluralsight.com/courses/rspec-the-right-way
* https://www.codeschool.com/courses/testing-with-rspec

**Comment by chandanaGollapudi** [comment]
Your answers are very clear and helpful . It makes my work easy.thank you so much for your help.
