### ISSUE TITLE
Confusion with `subject!`

### ISSUE THREAD

**Issue by thermaldonkey** [rspec/rspec-core#1958]
I've already read through the discussion on https://github.com/rspec/rspec-core/issues/1021 and don't think this to be a duplicate.

I'm trying out `subject!` for the first time, and am not quite sure if I'm misreading the documentation, or if there's something missing from them.

When I specify a `subject!` but I also define a simple `before` block, the subject runs first. When the docs said `subject!` executed within "a before block", I figured it would be run as the _last_ before block. Is that not what's intended?

**Comment by myronmarston** [comment]
`subject!` declares a `before` block at the call site.  `before` blocks run in declaration order, so, for example, this spec:

``` ruby
RSpec.describe "Stuff" do
  before { puts "1" }
  before { puts "2" }
  it { }
end
```

....prints `1` followed by `2`, since the first `before` hook runs than the 2nd one.  You get the same printed result if you use `subject!` for one of them instead:

``` ruby
RSpec.describe "Stuff" do
  subject! { puts "1" }
  before { puts "2" }
  it { }
end
```

Likewise, if you swap the order of `subject!` and the `before` hook they again run in declaration order:

``` ruby
RSpec.describe "Stuff" do
  before { puts "1" }
  subject! { puts "2" }
  it { }
end
```

That means that you are in complete control about when the `subject!` block gets run relative to other `before` hooks.  If you want it to run first, put it first.  If you want it to run last, put it last.

That said, the presence of a feature in RSpec doesn't mean it should be used in every situation.  I've personally never used `subject!`.  I have used `let!` occasionally and it seemed good to have `subject!` for `let` vs `subject` parity.  If your spec relies upon the order in which the `subject!` block runs to pass, I think you're better off not using `subject!` at all -- just order stuff in the correct sequential order in a `before` hook or an example.

**Comment by thermaldonkey** [comment]
:+1:
