### ISSUE TITLE
Warn about `subject` in `it` in the same manner as `let`

### ISSUE THREAD

**Issue by 3ube** [rspec/rspec-core#1970]
When `let` is used in `it` like this
```ruby
RSpec.describe 'Whateva' do
  it "disallows let in it" do
    let(:one) { 1 }
    expect(one).to be_truthy
  end
end
```
RSpec fails the example with
```
Failures:

  1) Whateva disallows let in it
     Failure/Error: let(:one) { 1 }
       `let` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).
```

Shouldn't the same be done for `subject` calls?
```ruby
RSpec.describe 'Whateva' do
  it "allows subject in it, " do
    subject { false }
    expect(subject).to be_truthy
  end
end
```

Currently the second example passes, but `subject` in `expect` is the RSpec's implicit one and not what was set in block.

**Comment by JonRowe** [comment]
Hm, this would require more logic than I'd like, the thing with `let` is it's so rarely encountered it can just raiser from inside the test, but subject is a genuine use case we'd have to check for arguments / a block everytime...

**Comment by myronmarston** [comment]
As @JonRowe said, `subject` is a very different case from `let` here.  `let` is only available from an example group (not an example), whereas `subject` is available off of both.  Since `let` is only available in one context, not the other, it was trivial to provide a nice error for it by handling `method_missing`.  In fact, in #1819, we were able to trivially provide nice errors for _any_ of RSpec's APIs that are called from the wrong scope (e.g. `describe`, `it`, `before`, `after`, `around`, `expect`, `allow`, `double`, `spy`, etc), not just `let`.

This technique obviously won't work for `subject` because there are two versions of the method: from an example group, it defines what the subject is, and from an example, it accesses the defined subject.  Given that, we'd have to put logic that would perform a runtime check every time `subject` is called, even when called correctly, which would impose a perf penalty on everyone who uses the feature.  Also, typical ruby semantics are that an extra unused block is ignored rather than triggering an error.  Thus, adding an error when `subject` is called from within an example with a block could be a breaking change.

Closing.
