### ISSUE TITLE
Nested conditionals will nullify outer conditionals

### ISSUE THREAD

**Issue by jdeff** [rspec/rspec-core#1976]
Given the following spec, I would expect that all examples would be filtered out.

```ruby
context 'when the outer conditional is false', if: false do
  context 'and the inner conditional is true', if: true do
    it 'does not run this example' do
      expect(true).to eq(true)
    end
  end
end
```
Unfortunately, the inner context is still running.

**Comment by myronmarston** [comment]
This is working as designed.  Filtering is applied to _individual examples_ (not example groups) and examples (and nested groups) are free to override the metadata that is set at the example group level.  This is what you are doing here.

I understand the confusion, though; `if` is named after a traditional conditional and it's not exactly mirroring the behavior you'd get out of a traditional conditional!  If you want a traditional conditional, you can use one:

``` ruby
if false
  context 'when the outer conditional is false' do
    if true
      context 'and the inner conditional is true' do
        it 'does not run this example' do
          expect(true).to eq(true)
        end
      end
    end
  end
end
```

Actually, we've tossed around the idea of deprecating the `if` and `unless` metadata, partly due to the potential for confusion.  The original use case (#167) no longer exists now that there is no longer a block form of `pending`.
