### ISSUE TITLE
Feature idea: autoretry failures

### ISSUE THREAD

**Issue by samphippen** [rspec/rspec-core#1979]
To my observation, it's not uncommon to write (e.g. integration) specs that are flakey, but you only need to see them pass once to assert that they are actually passing. I think we could add a metadata e.g. `:retry => true` or `:retry => 3` to indicate how many times a spec should be re-run if it fails.

One potential immediate practical application of this is to apply it to feature specs that have JS enabled in rails apps, which I've definitely seen flake.

One possible downside of doing this: it could compound cross-test state dependencies, but we could(?) turn it off during bisection.

Thoughts?

**Comment by cupakromer** [comment]
I against a feature like this being in "core". Personally I feel it would encourage people to write poor tests or enable people to hide real issues in their code because a test "sometimes" fails. There are several gems that already provide this type of functionality which people are free to use if they wish.

Specifically in regards to the JS issue, the test is "flaky" simply due to the nature of how that type of test behaves. Namely, in rspec-rails the default is to use Capybara, which spins up external processes, to perform the test. This asynchronous nature can cause the test to "sometimes" fail due to latency. Capybara already handles this case with a configuration setting on how long it waits before it considers one of it's matchers should fail.

The [semaphore](https://semaphoreci.com) CI host recently published a blog post related to this:  https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

They cover this JS case, specifically with Capybara. They discuss using polling instead of "retrying" a spec due to non-deterministic wait times. I tend to agree with this philosophy currently.

**Comment by myronmarston** [comment]
My instincts are similar to Aaron's -- this isn't a solution to flakiness I would generally recommend to users, and as such, I hesitate to include it in `rspec-core`, especially given that it's pretty easy to layer on top with a plugin.

**Comment by JonRowe** [comment]
Yeah as much as flakey tests are a pain I don't think this should exist in core.
