### ISSUE TITLE
ExecutionResult is coming back empty

### ISSUE THREAD

**Issue by chris1248** [rspec/rspec-core#2011]
For our rspec framework, here at work we wanted to tie in the results to an external website.

So I registered some functions to be executed after the examples in my rspec tests.
Like so:

    RSpec.configure do |config|
      config.after(:example) do |example|
        puts "finishing up test: #{example.metadata[:description]}"
        result = example.execution_result
        puts "   result #{result.inspect}"
        stat = result[:status]
        puts "   result status #{stat}"
      end
    end

But at runtime the status of the result of the execution is empty. Meaning variable 'stat' above is nil. 
I have no idea why. Thus I cannot determine if the test passed, or if it was skipped, or nothing. The only data on the result is when the test was started. Oh yay, just want I always wanted to know!! (NOT)

**Comment by myronmarston** [comment]
In RSpec 3, `execution_result` is no longer a hash -- it's an object with defined attributes:

https://github.com/rspec/rspec-core/blob/v3.3.1/lib/rspec/core/example.rb#L475-L554

We still present the hash interface for backwards compatibility but I'd recommend using `result.status` instead of `result[:status]`.

Anyhow, the status is not set until AFTER the `after` hooks run.  That is intentional because the `after` hook is itself part of the example, and if an exception occurs in the `after` hook we'll set the status of the example to `:failed`.  `after` hooks are great for cleanup/teardown logic but isn't intended for observing the status of examples.  Instead, I recommend you use a formatter for that:

``` ruby
class StatusFormatter
  RSpec::Core::Formatters.register self, :example_passed, :example_pending, :example_failed

  def initialize(out)
    @out = out
  end

  def example_finished(notification)
    example = notification.example
    @out.puts "finishing up test: #{example.metadata[:description]}"
    result = example.execution_result
    @out.puts "   result #{result.inspect}"
    stat = result.status
    @out.puts "   result status #{stat}"
  end
  alias example_passed example_finished
  alias example_pending example_finished
  alias example_failed example_finished
end

RSpec.configure do |c|
  c.add_formatter 'progress'
  c.add_formatter StatusFormatter
end
```

**Comment by chris1248** [comment]
Well stated. I'll try your example and report how it worked.
