### ISSUE TITLE
Support array order matchers

### ISSUE THREAD

**Issue by ioquatix** [rspec/rspec-core#2077]
https://rcode5.wordpress.com/2013/06/07/custom-rspec-matchers-for-arrays/

I think it would be awesome if these were adopted into rspec core.

**Comment by JonRowe** [comment]
RSpec core contains no matchers, you are thinking of rspec-expectations

**Comment by JonRowe** [comment]
Additionally the reason why we have a DSL for creating rspec matcher is for exactly this sort of situation, where someone wants a very specific kind of matcher, you can see how easy it was for the original author to create those matchers yet in the two years since it was published you are the first person to ask for these matchers. Thus they should stay out of the main rspec projects but you are welcome to publish an extension gem containing them.

**Comment by ioquatix** [comment]
Okay cool :)
