### ISSUE TITLE
Error in after(:all) hook doesn't fail rspec

### ISSUE THREAD

**Issue by xam7247** [rspec/rspec-core#2084]
For my tests, I have the following hooks in my spec_helper:
```ruby
RSpec.configure do |config|

  config.before(:all) do
    setup
  end

  config.after(:all) do
     teardown
  end

end
```
And the teardown method has some logic for failure:
```Ruby
def teardown
  # if some logic
    raise "Error occurred in after_all hook"
end
```

Now, when I execute my tests, and the after(:all) hook fails, it prints the error on console output, all specs have passed (which is right), but the overall execution is passed and ends with exit code 0.
I don't understand why we do not fail rspec execution if a after hook failed. 

PS: This is also evident in https://www.relishapp.com/rspec/rspec-core/v/2-2/docs/hooks/before-and-after-hooks#failure-in-after(:all)-block

Any help/explanation will be much appreciated.

**Comment by myronmarston** [comment]
This is working as designed -- although perhaps we can improve that design.

In general, `after` hooks are meant for teardown/cleanup, not for assertions or other test lock.  `after(:all)` even more so -- at the point it runs, the examples in its group have all been reported to the formatter as having passed or failed based on their own status so there's no chance for a failure in an `after(:all)` hook to affect the pass/fail status of the examples in its group.

We could potentially make `after(:all)` trigger RSpec to exit with a failing exit status (e.g. 1 instead of 0) but there are a few issues with that:

* RSpec doesn't currently have any concept of outside source of failure -- the suite pass/fail status is based on whether or not all specs passed or not.  Having all specs pass but the suite fail due to an `after(:all)` hook failure is a bit weird.
* If teardown/cleanup logic encounters a failure, it's not clear that what you want is a failure, anyway.  For example: if you're `after(:all)` hook tries to delete a temporary log file, and fails...do you care enough to make it fail your suite?
* Given that `after(:all)` hook failures don't currently cause a suite failure, and that for some users, having the suite fail would be undesirable, making this change now would be a breaking change.  We could make this change in RSpec 4, though.

Thoughts?

**Comment by xam7247** [comment]
Thanks @myronmarston . That's what I thought that this is by design.  

My opinion is that it should be consistent. If the before(:all) hook(s) fail the process, so should after(:all). And if any part of the process fails - be it trivial creation / deletion of temp files, it should exit with status 1. 

The issue this current behaviour causes is that it makes a build job (say: hudson) pass even when the teardown has failed. And our teardown does a crucial task - reverting application flags to pre-test state.  Hence, we missed to identify a potential problem in our test setup for quite a while, since the tests kept passing and further builds proceeded without a red herring. Rather undesirable :(

Would greatly appreciate if this is updated in RSpec4. Awaiting some more opinions and thoughts.

**Comment by JonRowe** [comment]
I think I'm mildly in favour of changing this behaviour in 4, or at least adding in a opt-in mode to enable this. Having errors in your test suite is kind of a smell so it'd be nice to have a strict mode to allow people to enforce not having them..

**Comment by samphippen** [comment]
I think we should make it a config option:

```
config.evaluate_after_all_blocks_strictly = true/false
config.treate_errors_in_after_all_blocks_as_failures = true/false
```

or similar. We could add that now, and then decide whether or not to turn it on or not in RSpec 4 later.

**Comment by JacobEvelyn** [comment]
I agree that this would be a nice config option to have.
