### ISSUE TITLE
Proposal: A context containing only measurement examples that share a cached subject

### ISSUE THREAD

**Issue by boffbowsh** [rspec/rspec-core#2087]
The recently-added `aggregate_failures` feature allows a lot of speedup of tests where setup is expensive and lots of examples need to be evaluated. I'm thinking it'd be useful to be able to define a context where all examples within will run with the same cached subject, without the need for the setup to be performed between each example. 

In the example below, the rendered expensive page can be re-used between the multiple examples without any issues of interdependencies, plus also allows developers to continue following the betterspecs rule of [Single expectation tests](http://betterspecs.org/#single). 

```ruby
  describe "an expensive page", cached_subject: true do
    subject { visit "/"; page }
  
    it { is_expected.to have_css "title", text: "Foo" }
    it { is_expected.to have_css "h1", text: "Bar" }
    # ...
  end
```

I'd like to do the work to make this happen, I wanted to first check that I hadn't overlooked anything in the design of this, or if anyone has any pointers about implementation. Would this be welcomed in core, or better released as a gem?

**Comment by myronmarston** [comment]
The easy way to implement this is with a `before(:context)` block and an instance variable:

``` ruby
  describe "an expensive page" do
    before(:context) { visit "/"; @page = page }
    subject { @page }

    it { is_expected.to have_css "title", text: "Foo" }
    it { is_expected.to have_css "h1", text: "Bar" }
    # ...
  end
```

This generally works (although it comes with some gotchas, as I'll explain in a second) without the need for any new APIs or gems, and has the advantage of not hiding the implementation so that when something goes wrong with this approach (and it inevitably will, due to the gotchas), you're left wondering how the feature works.

This has a number of gotchas/downsides, as I said:

* If any example mutates the `subject`, you could have subtle ordering dependencies.
* Because the expensive logic has been moved into a `before(:context)` hook, you can't use any per-example RSpec constructs.  That includes `let` declarations and all rspec-mocks features.
* If you're using rspec-rails w/ transactions enabled or DatabaseCleaner or any other gem that manages a per-example test DB transaction lifecycle, you're likely to run into major problems with this approach because the `before(:context)` hook runs _outside_ the context of an example and thus isn't wrapped in a DB transaction.  Among other things, that means that if you mutate the DB in whatever action you take in `before(:context)`, the DB mutations will be left behind and will be visible from subsequent examples, which is a great way to create unintentional ordering dependencies between different parts of your test suite.

One slightly different approach which could address some of these concerns is to do the following:

``` ruby
  describe "an expensive page" do
    cached_subject = nil
    subject { cached_subject ||= (visit "/"; page) }

    it { is_expected.to have_css "title", text: "Foo" }
    it { is_expected.to have_css "h1", text: "Bar" }
    # ...
  end
```

Here we've moved the slow logic out of a `before(:context)` hook and back into the `subject` declaration, but written it in such a way that it'll only be executed once for the first example; for subsequent example the cached value will get used.  This addresses some of the issues mentioned above (particularly the issue with DB transactions) and is pretty simple to understand.

All that said, I wouldn't recommend this approach _at all_.  You mentioned `aggregate_failures` -- why not just use that?

``` ruby
  example "an expensive page", :aggregate_failures do
    visit '/'

    expect(page).to have_css "title", text: "Foo"
    expect(page).to have_css "h1", text: "Bar"
  end
```

IMO, this is the simplest, best solution.  There's no extra cognitive overhead of having to understanding how `subject` and `is_expected` relate.  You're explicitly visiting the page once and then making multiple expectations about it.  This version is going to run the fastest as it avoids the extra overhead of the setup/teardown that RSpec does for each example.  `aggregate_failures` ensures you get to see all of the failures and not just the first one.  We specifically added `aggregate_failures` for these situations so that's our recommended approach.

What this doesn't do is follow some arbitrary "one expectation per example" from betterspecs.org but the guidelines from that site aren't what I would endorse, anyway.  The _point_ of the "one expectation per example" guideline is to be able to see multiple failures from a single suite run rather than just seeing the first one and also to encourage you to keep each unit test focused on describing a single facet of behavior.  Once you're involving some slow operation you're not really doing unit tests anymore, though.

If you still want to add an API to do what you're asking it would belong in a gem, and not in core.  For reasons I've stated here it's not a practice we want to encourage.
