### ISSUE TITLE
Duplicate definition of SHELLS_ALLOWING_UNQUOTED_IDS in shell_escape.rb

### ISSUE THREAD

**Issue by bitcababy** [rspec/rspec-core#2099]
`SHELLS_ALLOWING_UNQUOTED_IDS = %w[ bash ksh fish ]` 
 should be
 `SHELLS_ALLOWING_UNQUOTED_IDS = %w[ bash ksh fish ] unless defined?(SHELLS_ALLOWING_UNQUOTED_IDS)`

**Comment by myronmarston** [comment]
We don't generally put `unless defined?` checks.  They are a code smell that hides the fact that a file is being loaded twice when it shouldn't be. Far better to restructure your requires/load_path so that the file isn't loaded twice.

What concrete problem are you having?  Are you getting a warning from Ruby about this constant?  As far as I can see, this constant is only defined in one place in our code base so it shouldn't cause any warnings unless the file is loaded twice, but that generally shouldn't happen with how we've structured things.  If it is, I'd like to get some repro steps from you so we can address it.

**Comment by bitcababy** [comment]
Yeah, I'm getting complaints. I did a "rake routes" and got
`/Users/mer/.rvm/gems/ruby-2.2.3@global/gems/rspec-core-3.3.2/lib/rspec/core/shell_escape.rb:30: warning: already initialized constant RSpec::Core::ShellEscape::SHELLS_ALLOWING_UNQUOTED_IDS
/Users/mer/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/shell_escape.rb:30: warning: previous definition of SHELLS_ALLOWING_UNQUOTED_IDS was here`

**Comment by myronmarston** [comment]
Thanks for explaining that.  I have a fix for this in #2101.
