### ISSUE TITLE
example_status_persister can't find status_id

### ISSUE THREAD

**Issue by macosgrove** [rspec/rspec-core#2107]
Every so often when we run our test suite, we get `undefined method 'split' for nil:NilClass (NoMethodError)` here: https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/example_status_persister.rb#L134

Looks like for some reason it's not finding the scoped_id.

Here's an example stack trace:
```
/var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:134:in `sort_value_from': undefined method `split' for nil:NilClass (NoMethodError)
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:90:in `each'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:90:in `sort_by'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:90:in `merge'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:76:in `merge'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:39:in `merged_statuses'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:35:in `dumped_statuses'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:24:in `persist'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_status_persister.rb:15:in `persist'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:125:in `persist_example_statuses'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:90:in `block in run'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `tap'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /var/lib/buildkite-agent/builds/market-ip-10-0-0-8.ec2.internal/envato-marketplaces/marketplace/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from bin/rspec:16:in `load'
	from bin/rspec:16:in `<main>'
```

**Comment by myronmarston** [comment]
Thanks for reporting this!  It's not clear to me what the source of this bug is.  Looking at the [line you referenced](https://github.com/rspec/rspec-core/blob/v3.3.2/lib/rspec/core/example_status_persister.rb#L134), the error could only happen if `scoped_id` is `nil`, and _that_ could only happen if the `split` on the prior line did not return 2 parts.  The [split pattern](https://github.com/rspec/rspec-core/blob/v3.3.2/lib/rspec/core/configuration.rb#L1718) is designed to split the file name and `scoped_id` parts and should always work as long as id is in the form of `<file_name>[<scope_id>]`.  So the error you got suggests that somehow the id was _not_ in that form.  However, [that's the way we format example ids](https://github.com/rspec/rspec-core/blob/v3.3.2/lib/rspec/core/metadata.rb#L103-L105) so I'm puzzled how it got in this state.

There are a few ideas I can think of:

* Maybe something (or someone) is editing the example persistence file, adding mangled ids to the mix.
* Maybe something is mutating the example ids on the RSpec examples somehow (e.g. a poorly behaved extension gem).

Regardless, I'm not able to address this bug without more info.  Any chance you can put together a reproducible example?  If not, try this patch in your project:


``` ruby
module PrintProblematicIDs
  def sort_value_from(example)
    super
  rescue
    puts "Example id #{example.fetch(:example_id).inspect} could not be parsed"
    raise
  end
end

RSpec::Core::ExampleStatusMerger.prepend PrintProblematicIDs
```

This won't solve your problem but should print out the ID that's causing the problem so we can see what it looks like.  From there hopefully we can diagnose further and fix the problem.

**Comment by samphippen** [comment]
@macosgrove would you mind putting the patch myron posted in your `spec_helper` and rerunning your test suite until it gives some output? We'd love to have a repro case for this.

**Comment by myronmarston** [comment]
Closing due to lack of response.  If someone is able to provide the requested output we can reopen.

**Comment by pjscopeland** [comment]
I had a similar issue in a different line... it turned out that another of my libraries (intended to modify the `String` class) was interfering somehow. When I took that out, it worked again.
