### ISSUE TITLE
Using config.seed or --seed without random ordering

### ISSUE THREAD

**Issue by soulcutter** [rspec/rspec-core#2116]
I was considering using `Kernel.srand config.seed` without random ordering in order to supply a random seed via the command line. In doing so, I realized RSpec forces random ordering if you specify a seed. Also, despite having 'used' `config.seed` RSpec will not print the seed in the output. `config.seed` is accessible

Does it make sense to allow `seed=` without forcing random ordering? I'm on the fence, so wanted to discuss it before throwing up a PR if we consider this to be the correct behavior. A user could specify an environment variable as a random seed to get around the forced-ordering behavior.

FWIW the command-line documentation states: 

`--seed SEED                  Equivalent of --order rand:SEED`

Not the thrust of this issue, but is there a reason for RSpec -not- to `Kernel.srand config.seed`? I suspect there's a good reason, but I'm struggling to conceive of it

**Comment by myronmarston** [comment]
> Not the thrust of this issue, but is there a reason for RSpec -not- to `Kernel.srand config.seed`? I suspect there's a good reason, but I'm struggling to conceive of it

An attempt was made to have RSpec do `Kernel.srand config.seed` (see #1100) but it turns out to be far more complicated to get right for all situations than you'd think.  In particular, it was hard to make it work right for `rspec --seed 1234` and `config.seed = 1234` and to make both of those work right when a forking runner such as spring was being used.  After discussing all those issues (read the comments in #1100 for the full story) we decide it was far simpler and more consistent to take a "hands off approach":  RSpec doesn't do anything with the global randomization seed (choosing to use an isolated random number generator so our use of randomization doesn't interact with the user's use of randomization), and the `Kernel.srand config.seed` call is merely a suggestion that allows the user to make the `--seed` option apply to all randomization in their test process.

> Does it make sense to allow seed= without forcing random ordering? I'm on the fence, so wanted to discuss it before throwing up a PR if we consider this to be the correct behavior.

I think that part of #1100 was an attempt to allow `seed=` w/o random ordering.  Regardless, making it so that `--seed abcd` does not trigger random ordering would be a breaking change from documented behavior so it can't really be done in 3.x if we're going to stick with SemVer.

> A user could specify an environment variable as a random seed to get around the forced-ordering behavior.

Alternately, I _think_ this would work:

``` ruby
# spec_helper
RSpec.configure do |c|
  Kernel.srand c.seed
  c.order = :defined
end
```

This would force the ordering back to `:defined` (rather than `:random`) w/o affecting the seed.

On a side note, why are you trying to avoid random ordering?

**Comment by soulcutter** [comment]
> On a side note, why are you trying to avoid random ordering?

TBH I'm not - I always use random ordering. It's something that I thought would be possible, though. The idea of setting a seed used by RSpec's randomization is independent of how it actually gets used in my mind.

> the `Kernel.srand config.seed` call is merely a suggestion that allows the user to make the --seed option apply to all randomization in their test process.

Yeah, I think that's what made me think of using the `config.seed` value more generically rather than tied to ordering.

Thanks for digging up the background on Kernel.srand - deep down I knew there must be something :wink: I also agree it would be a breaking change according to SemVer. It doesn't seem necessary unless there's some other RSpec use of random.
