### ISSUE TITLE
Misleading warning for `shared_context`s with «meta» attributes

### ISSUE THREAD

**Issue by jibiel** [rspec/rspec-core#2123]
Greetings, gentlemen.

So I wanted to be a smartass and keep the same name for the different spec types:

```ruby
# This shared context is available for both `:feature` and
# `:controller` specs, utilizing `Warden` and `Devise` helpers
# correspondingly. No need to specify `type` in `:controller` specs.
shared_context :current_user, type: :feature do
  let(:user) { create :user }

  before do
    login_as user, scope: :user
  end
end

shared_context :current_user do
  let(:user) { create :user }

  before do
    sign_in user
  end
end
```

And it works great, but know I'm getting this warning:

```
WARNING: Shared example group 'current_user' has been previously defined at:
  ~/dev/ruby/apps/{...}/spec/support/shared_contexts/current_user.rb:4
...and you are now defining it at:
  ~/dev/ruby/apps/{...}/spec/support/shared_contexts/current_user.rb:12
The new definition will overwrite the original one.
```
The thing is that the new definition __isn't overwriting the original one__. They behave as expected in the `:feature` and `:controller` specs correspondingly.

Apologies for my ignorance, I don't know if those attributes supported or how the `shared_context` method implemented, but those `context`s are definitely treated as different ones and the warning logic should probably be updated.

**Comment by myronmarston** [comment]
> The thing is that the new definition **isn't overwriting the original one**. 

This is only partially true.  Here's what's going on:

* When you define `shared_context :current_user, type: :feature` it stores the passed block in two places:
  * In `RSpec.world.shared_exampole_group_registry` it gets stored under the `:current_user` key.
  * Because there is attached metadata, a `RSpec::Core::SharedExampleGroupModule` instance with a reference to the block gets stored in `@include_modules` in `RSpec.configuration` with `:type => :feature` metadata.
* When you define `shared_context :current_user` it overwrites the shared group block stored in `RSpec.world.shared_example_group_registry` under the `:current_user` key.  The reference in configuration with the `:type => :feature` metadata is not replaced.

So the new definition is _definitely_ overwriting the original one in `RSpec.world.shared_example_group_registry` and that's what the warning is about.  However, there is a copy stored in `RSpec.configuration` so that the metadata-based inclusion can work, and that is _not_ overwritten and as a result it is working for you.

So, a few thoughts:

* While it's slightly confusing, the warning still has merit in this situation because the shared group is being overwritten in the main registry.
* The shared group name (`:current_user`) is designed to be a primary way to reference and include the shared group, and naturally you can't have two groups with the same name.  Is there a reason you need the name of the first group to be `:current_user`?  Since it is overridden in the name registry there's no way you can include it by name so the name doesn't seem to matter to you -- so I'd suggest renaming it (to something like `:current_user_for_feature_specs`).  Then there's no name conflict and no warning.
* The mechanism you are using for shared group inclusion via metadata is slated for deprecation and replacement with something simpler and more consistent in RSpec 4.  See #1790.  It'll still allow you to include a shared group based on metadata but would avoid the issue you've run into entirely.

**Comment by jibiel** [comment]
@myronmarston Thanks for the quick and detailed response.

> Is there a reason you need the name of the first group to be `:current_user`?

Nothing serious, just trying to keep things simple since the code doing basically the same thing (from the point of view of the developer writing specs) apart from the fact that it uses valid helpers for each of the spec types. And besides, naming hurts.

I was aware of the `:current_user_for_feature_specs` option, thanks. It's just lacks of style, you know.

Ok, I hear you, and what about passing block variables?

```ruby
shared_context :current_user do |type|
  # ...
end
```

Will this approach be deprecated too?

**Comment by myronmarston** [comment]
The block variables are here to stay.

**Comment by jibiel** [comment]
That's nice, thanks!
