### ISSUE TITLE
~/.rspec ordering beats Rspec.config { |c| c.order }, and it probably shouldn't. 

### ISSUE THREAD

**Issue by sgrif** [rspec/rspec-core#2126]
@samphippen and I are pairing on getting Rails 5 working with Rspec, and this came up. When I run the rspec-rails suite, it will fail on my local machine, because I have a `~/.rspec` which specifies `--order random`. When we get to tests which specify `order = :defined` in a config block, they fail on my machine.

Example Rspec project:
https://github.com/sgrif/rspec-dotfiles-example

Run output, including ruby version and `~/.rspec` contents
https://gist.github.com/sgrif/e8b8d31a031b7ee1fde4

**Comment by myronmarston** [comment]
It's by design that settings in `~/.rspec` take precedence over settings set via `RSpec.configure { }`.  The idea is that a user's preferences should override project defaults.  So, for example, a project may choose to use the progress formatter as its formatter, but a user may prefer the documentation formatter and can get that on all projects by adding `--format doc` to `~/.rspec`.  Likewise, maybe some users like seeing full backtraces and others don't.  The project can have a default and individual users can override that with their preferences in `~/.rspec`.

We could potentially treat particularly config settings differently and not allow values in `~/.rspec` to take precedence but that's a complex, confusing path that I don't think I want RSpec to go down.  Having a consistent "config values in ~/.rspec take precedence" rule seems important.

I'd argue that since `~/.rspec` is designed to allow you to override config settings on any project, you should only put settings there that are safe to run on all projects you might run.  Random ordering is really a project-level thing -- either a project's test suite has ordering dependencies (in which case no one can run the tests in random order) or it doesn't have ordering dependencies (in which case the team working on a project will probably want `order = :random` on for everyone so everyone sees ordering dependencies when they surface).

**Comment by sgrif** [comment]
Cool. We just weren't sure the intended behavior. Makes sense.

**Comment by JonRowe** [comment]
++
