### ISSUE TITLE
[Feature] warn about nil comparizon

### ISSUE THREAD

**Issue by jonatas** [rspec/rspec-core#2160]
Hi, today I was reviewing some specs and I get a nice hidden problem in a assertion in a case like these:

```ruby
let(:the_right_key) { :some_nice_key }
it 'fetches the nice key' do 
  expect(hash[:key]).to eq(other_hash[:the_right_key))
end
```

In fact, it was a typo on `other_hash[:the_right_key]` instead of `other_hash[the_right_key]`.

But, both hashes does not have the key and it starts comparing nil with nil.

My suggestion is about **warn** the developer about the nil and suggest to use `expect(...).to be_nil` instead of comparing `nil` using `eq`.

What do you think about these?

**Comment by myronmarston** [comment]
There are a few ways you can handle this yourself, without any changes needed in RSpec.  For one, the `include` matcher is designed for use with hashes (and other collection) types, and if you changed your expectation to:

``` ruby
expect(hash).to include(key: other_hash[:the_right_key])
```

...then you would get a nice failure:

```
     Failure/Error: expect(hash).to include(key: other_hash[:the_right_key])

       expected {} to include {:key => nil}
       Diff:
       @@ -1,2 +1 @@
       -[{:key=>nil}]
```

Another option is to implement the warning yourself. Using simple ruby, you can make _any_ matcher warn when it receives _any_ argument -- rather than RSpec being burdened with an inflexible option that only warns for `eq` receiving `nil`:

``` ruby
module MatcherOverrides
  def eq(value)
    warn "eq called with nil" if value.nil?
    super
  end
end

RSpec.configure do |c|
  c.include MatcherOverrides
end
```

Since we already provide a matcher for hashes that guards against this, and you can add the warning yourself with minimal code, I don't think any change is necessary to RSpec itself.
