### ISSUE TITLE
RFE: Add line numbers to --format documentation output

### ISSUE THREAD

**Issue by atodorov** [rspec/rspec-core#2168]
I don't see such an option and it would really be useful. Currently I'm using the line numbers reported by less (or other tools) to check which tests have been executed prior to a failing one when dealing with flaky tests. 

I may be able to work on a patch for this issue, how do you prefer to implement it ?

**Comment by myronmarston** [comment]
> Currently I'm using the line numbers reported by less (or other tools) to check which tests have been executed prior to a failing one when dealing with flaky tests.

This sounds like you're trying to solve the same problem for which we built [`--bisect`](https://relishapp.com/rspec/rspec-core/v/3-4/docs/command-line/bisect).  Have you tried using `--bisect`?

Anyhow, I don't think line numbers generally belong on the documentation output, because I think it runs counter to the documentation formatter's purpose -- showing human readable documentation.  We could make it a config option but the more general approach we've taken is to make formatters easy to write and select via a config option.  So this could easily be implemented as a gem, and then users could use it by installing it and using a `--format` option.
