### ISSUE TITLE
Proposal: focus within focus should run "inner" specs.

### ISSUE THREAD

**Issue by georgeu2000** [rspec/rspec-core#2218]
Use case: You focus a single spec by adding the focus tag on the `describe` at the top of the spec. Then you want to run a single spec and focus it. The existing behavior is to run the entire file, instead of the "inner" focussed spec.

The problem with this behavior is that it takes a long time to run the whole file. Faster feedback would be provided by running the inner spec only. In this case, the user forgot to unfocus the top `describe`. But this could provide a good work flow allowing the dev to dig down and fix one spec at a time, and then when they are finished the whole file would be run.

Not sure if this has been discussed, but didn't find any relevant issues. If opinions are divided, we could add a config for this.

I would be happy to do a PR.

**Comment by JonRowe** [comment]
This isn't possible due to the way our metadata works, you have to remove the top level focus if you want just the inner focused example.

**Comment by myronmarston** [comment]
To expand on what @JonRowe said: RSpec's metadata is modeled in a simple way where examples inherit metadata from their example group and nested example groups inherit metadata from their parent group.   Filtering (including `:focus` filtering) is then applied on an example-by-example basis by looking only at its metadata.

That means that when you tag `describe` with `:focus`, filtering works because each example inherits `:focus` metadata from the group.  There isn't any way that I can think to get the behavior you want without changing how metadata inheritance works across the board or by treating `:focus` as a special metadata key that has different inheritance semantics.  Both of these options are unappealing and would cause lots of confusion.

To get the behavior you want, just remove the `:focus` metadata from the example group and tag the example you want to focus instead.  We've tried to make this easy by providing aliases that allow you to add and remove `:focus` metadata by adding and removing a single character; use `fdescribe` and `fcontext` and `fit` for focused versions of `describe`/`context`/`it` and then remove the leading `f` for unfocused versions.
