### ISSUE TITLE
exclude_pattern=  does not seem to work from within RSpec.configure block

### ISSUE THREAD

**Issue by bertBruynooghe** [rspec/rspec-core#2225]
This is what I'm trying to achieve:

    RSpec.configure do |config|
      if some_condition
        config.exclude_pattern=  '**/dummy/spec/models/post_spec.rb'
      end
    end

but the test in post_spec.rb are still executed.   
(I also don't get a warning, and ```putting puts("**** #{config.files_to_run}")``` seems to take the the pattern into account.)  
Also, using the exclude_pattern from the command line does seem to work.

**Comment by bertBruynooghe** [comment]
Awww, my bad. I was putting the above codeblock in _rails_helper.rb_, which is only required in the file I'm trying to exclude, so exactly in the file I'm trying to exclude. 
Fixed the issue by requiring ```rails_helper``` in _.rspec_...

**Comment by myronmarston** [comment]
FWIW, we recommend you avoid putting `--require rails_helper` in `.rspec`, since `rails_helper` loads rails and is quite heavyweight.  That means you have no way in your project to run RSpec w/o loading Rails, which means you have no way to get fast, subsecond test feedback when writing specs against components that do not depend upon rails.  For configuration that you want to always be loaded, we recommend you put it in `spec_helper`, which is meant to be light weight and always loaded.  Is there any reason that wouldn't work for you?

**Comment by bertBruynooghe** [comment]
I came to think the same just a few moments ago, so I already applied your suggestions :)
Thanks anyway!
