### ISSUE TITLE
Patching `output` for formatters when --tty is used

### ISSUE THREAD

**Issue by jfelchner** [rspec/rspec-core#2229]
Hello all, I wanted to raise this since I'm not 100% sure where the proper place for this is.

When the `output` stream is used inside of the base formatter, it behaves as if it's a standard `IO` class instance.  Unfortunately, this `IO`-like thing (maybe it actually is an `IO`, I didn't check) responds `false` to `tty?` even when the `--tty` option is passed in to `rspec`.  Therefore anything downstream that uses that `IO`, if they perform different output based on `tty?`, the user won't get the results they expect.

I can monkey-patch this in fuubar, but I thought it was worth bringing up here since it seems like there may be a root issue that needs addressed.

Reference thekompanee/fuubar#88

**Comment by myronmarston** [comment]
So a few things...

* `--tty` doesn't do anything to the output stream (such as forcing it to be a TTY....if `$stdout` is a file or some non-TTY IO, RSpec can't make it a TTY).  It merely overrides RSpec's internal `tty?` check that would cause RSpec to ignore the `--color` option if the output is not a TTY.  (In affect, `--tty` acts like `--force-color`, forcing color even if the output does not appear to support it).
* `--tty` also isn't a documented public API (although, perhaps it should be, but I don't really know the story of how it originated as it predates my time on RSpec).  Long term, I think I'd like to see it go away, anyway; since color is always preferable (IMO, anyway), at least as long as the output can support it, it's suboptimal that users have to opt-in to it with `--color`, and then when users do opt-in, it's suboptimal that that another flag (`--tty`) is necessary to show that they _really_ meant it and force color output.  I think it would be a better experience if RSpec automatically printed in color if the output is a TTY, and supported `--color` to force it or `--no-color` to disable it, regardless of `output.tty?` status.
* I tried putting together a toy example to see if I can reproduce the issue you are seeing and I can't...or at least the behavior I'm seeing seems 100% correct.  Here's what I'm seeing:
  * When I run `rspec --formatter CustomFormatter` (no `--out` flag, so it prints to stdout by default), `output.tty?` in my custom formatter is `true`, as I'd expect.
  * When I run `rspec --formatter CustomFormatter --out out.txt`, `output.tty?` in my custom formatter is `false`, as I'd expect, since it's printing to a file, not a terminal.
  * Likewise, when I run `rspec --formatter CustomFormatter > out.txt`, `output.tty?` in my custom formatter is also `false`, as I'd expect, since it's printing to a file, not a terminal.
* Regardless, `output.tty?` is provided by Ruby to indicate if the output is a TTY or not. I can't think of a situation where we'd ever want RSpec to overwrite that method to make it lie.

Let me know if I'm misunderstanding you or if you've got an isolated example that demonstrates the issue that you'd like me to take a look at.

**Comment by jfelchner** [comment]
@myronmarston thanks for the detailed response.  I'm definitely on the fence myself as to whether I actually want to add this custom functionality to the formatter.  This particular individual's use case is that he's using a gem that's piping the RSpec output through a non-TTY stream, but they want everything to behave like TTY so that on the other side they can execute all the ANSI codes so that it looks like it was TTY all along.

The use case they're wanting is: `rspec --formatter Fuubar --tty > foo` and have `output.tty?` register as `true`.

Their rationale for this is that `fuubar` is just a very simple formatter and `ruby-progressbar` does all the heavy lifting.  If `ruby-progressbar` sees that the output is non-TTY, it knows that it can't do dynamic updates (which require carriage returns and a reprint of the bar) and therefore simplifies the output format so that it doesn't cause a lot of noise like [this](https://gist.github.com/jfelchner/f90532e9aaea9a1a0a85116e0562e145#file-tty-pb-output), instead you end up with a very clean bar like [this](https://gist.github.com/jfelchner/f90532e9aaea9a1a0a85116e0562e145#file-nontty-pb-output).  More info can be found [here](https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output)

So TTY in this case doesn't just mean "show or don't show colors", it actually causes a dramatic difference in the output itself.

If you're still adamant about the `--tty` option either getting removed or basically just being an alias for colors, then I'm even more hesitant about adding [this custom logic](https://github.com/thekompanee/fuubar/commit/184642517f949b9bca39826964034320988c6531) to fuubar.

**Comment by JonRowe** [comment]
You can set the output stream yourself programmatically, you could make it lie to the downstream stuff...

**Comment by jfelchner** [comment]
@JonRowe right now I'm wrapping `output` in a delegator class that lies about `tty?`.  Is that what you man?

**Comment by jfelchner** [comment]
I guess my other concern is supporting `--tty` if I'm using it in a way that you all aren't saying is compatible with the reason it's there.  If it's basically there for colors only, then I don't want to support it to do things other than that, but if it's there to force ANSI codes in general, then I will.

**Comment by myronmarston** [comment]
I just opened #2230 to document the direction I want to take things in RSpec 4.  Given `--tty` is undocumented and something I expect to go away, I think you'll be better off not depending on it and I'm not keen to expand what it does.  Wrapping the output in a delegator seems like a pretty good solution.
