### ISSUE TITLE
Simplify `--tty`/`--color`/`--no-color` semantics

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-core#2230]
Currently, the config options for colors are suboptimal:

* By default, colors are not displayed.
* `--color` opts-in to color
* ...unless the output is non-tty, in which colors are not displayed
* ...unless you pass the undocumented `--tty` option, which forces color even when the output is non-tty
* If `--no-color` is passed it turns color off.

The `--tty` option is undocumented and weird (and has caused some confusion; see #2229) and feels like it shouldn't be necessary.  In addition, it is suboptimal that we default to showing the user no color in the output even if they are on a TTY.  I think nearly everyone prefers color to no color.  So I'd suggest we change things up in RSpec 4:

* By default, show color (or not) based on if the output is TTY (or not).  This will usually do the "right thing" without any user intervention.
* Support `--color` (or maybe `--force-color`) to force color output even if the output is not a TTY.
* Support `--no-color` to disable color output even if the output is a TTY.

**Comment by e2** [comment]
> The --tty option is undocumented and weird (and has caused some confusion; see #2229) and feels like it shouldn't be necessary. 

I actually need colors forced, because sometimes color is desired, even if the app doesn't open a tty. (And example is using RSpec with http://gittup.org/tup).

The only time I don't want color is when I'm generating output for an editor. But that's what `--out` and `--format` and formatters are for.

So I'd say: always show color unless users want to disable it explicitly. 3 such cases I can think of:

1. Output for tools to parse (editors, etc.)
2. Broken terminal support and/or Windows without ansicon.
3. Tests dumping binary data to the output (which would screw up colors).

So disabling colors is a rare exception as I see it.

**Comment by JonRowe** [comment]
@myronmarston I agree we should go colour based on the nature of the output with `--force-color` and `--no-color` to alter the behaviour either way.

**Comment by CodingItWrong** [comment]
I'll give this issue a shot!
