### ISSUE TITLE
custom tool for generating .nav for Relish docs

### ISSUE THREAD

**Issue by e2** [rspec/rspec-core#2265]
After some work on reorganizing the docs for Relish, I decided to hack together a simple tool:

https://gist.github.com/e2/bf8dda7746275656f44835b86881beb6

What it does now:
1. Generates a .nav file from existing *.feature files in a given dir
2. Allows prepending entries that aren't in feature files (like Changelog)
3. It uses Gherkin to extract the feature name and tags

What it could do (with a little more code):
1. Verify that feature descriptions and file names match
2. Use special feature tags for metadata to be used for generating .nav (e.g. hiding feature from docs, ordering docs)

Idea for ordering entries in Relish: I think the most useful is to have the order alphabetical, and use special tags to override the order in Relish:
1. `@nav.before(feature_name2)` and `@nav.after(feature_name2)` would cause the current feature to appear before/after `feature_name2` in Relish. Useful for things that should be at the top/bottom.
2. `@nav.parent.before(feature_dir_name2)` (and an "after" version too), so that a feature file can order the directory it is in, e.g. "example groups" should come before "alternate mock frameworks".

Ok, the second version is weird (a feature file affecting the order the directory appears), but it eliminates a need for index files and/or syncing feature dir entries with Relish organizing.

One benefit would be less: manual work needed to add, organize and merge documentation. Tags may seem a bit messy for this, but they allow adding features automatically to Relish. (It would just take committing an automatically update .nav file).

Thoughts?

**Comment by JonRowe** [comment]
Tags will show up in relish, so I think our current solution of manually ordering the nav is better.

**Comment by myronmarston** [comment]
I really like the idea of an automated tool for this, but I'm not sure the approach you've taken here will work well.

> Idea for ordering entries in Relish: I think the most useful is to have the order alphabetical, and use special tags to override the order in Relish:

I don't think this is going to work well.  For one, the order we want generally has no relation to alphabetical ordering.  (See the rspec-mocks relish docs for example -- the items were very intentionally ordered).  I don't think assuming any kind of default order is going to work well enough.

The tag idea is also problematic because Relish renders the tags -- so I don't really want to add a bunch of tags to the features that don't mean anything to end users reading the docs.

> hiding feature from docs

AFAIK, there's no way to hide a feature file from the docs (I asked at one point).  If a feature file is not listed in `.nav` relish will just add it at the end.  Suboptimal, perhaps, but `.nav` was a later feature addition so the approach was necessary for backwards compatibility.

That's one reason I've mentioned wanting to remove any cukes that do not have documentation value.

I think there are a few automated things here that could be done, though:

* Validate that the feature file names align with the feature titles (ideally it would be a one-to-one mapping between the two).
* Validate that every feature file has been listed in `.nav` to ensure that human choice was made about where it best fits.

If you want to write up a tool that checks those things so we can add it to our build that would be useful.  If you do so, please add it to `rspec-dev` so that we can distribute it to the other repos in the same way we distribute our build scripts.

**Comment by e2** [comment]
I just had the idea to reuse the ordering of features and dirs from the existing .nav file. Solves the ordering problem, while the tool can add/remove added / renamed / removed features.

**Comment by e2** [comment]
I think it's better to have the tool modify the nav file instead of just showing warnings or errors.

And I totally agree with everything you said.

**Comment by JonRowe** [comment]
We just told you we didn't want that, you can have the script fail the build if a new file isn't present in the nav file.

**Comment by myronmarston** [comment]
Having it modify the `.nav` file seems problematic in that it's the canonical source of the ordering.  So modifying the canonical source seems like a bad idea.

OTOH, the `Feature:` name in the feature file is the canonical source of the name, because the conversion to a file name is a one-way function (e.g. punctuation gets indiscriminately turned into `_` in the filename so you can't turn back).

**Comment by e2** [comment]
Why not add/remove/modify entries automatically? No point in having a human being doing exactly the same thing. Besides people will likely notice the changed file and add it to their PR. Or at least ask about it.

I meant that it doesn't make sense to show those warnings and errors that are due to something the tool can work out how to deal with.

**Comment by JonRowe** [comment]
The CI build shouldn't modify the PR

**Comment by e2** [comment]
> The CI build shouldn't modify the PR

I don't mean the PR, just modifying the .nav file LOCALLY. This way if anyone add/removes/renames feature files, the .nav file changes and contributors will see it with `git status` (their local checkout won't be clean until they deal with the .nav file).

**Comment by JonRowe** [comment]
Theres no way to automatically run the tool locally, and it's more useful as part of the build and thus shouldn't modify files.

**Comment by e2** [comment]
> There's no way to automatically run the tool locally, and it's more useful as part of the build and thus shouldn't modify files.

I'll make it an option then.

**Comment by xaviershay** [comment]
> That's one reason I've mentioned wanting to remove any cukes that do not have documentation value.

+1 this, I was doing this on rspec-mocks.

Closing issue as stale, if you do come up with code to do the verification steps please do reopen as a PR! Thanks for poking around at it.
