### ISSUE TITLE
run_all_when_everything_filtered not working as expected

### ISSUE THREAD

**Issue by constantm** [rspec/rspec-core#2266]
I've tried implementing `run_all_when_everything_filtered` along with `rspec-retry` so that retries only run individual examples instead of whole specs on retry. 

On the first run of the spec with `rspec --only-failures`, it will find no failing tests and hence all examples will be filtered out. I was expecting the `run_all_when_everything_filtered` option to counteract this, and actually run the tests. 

Am I doing something wrong, or am I misunderstanding how `run_all_when_everything_filtered` works?

My config, shortened for brevity:

```ruby
# spec/spec_helper.rb
RSpec.configure do |config|
  config.example_status_persistence_file_path = "examples.txt"
  config.run_all_when_everything_filtered = true
end
```

```
# rspec --only-failures
Run options: include {:last_run_status=>"failed"}

All examples were filtered out

Randomized with seed 31670

Finished in 1.82 seconds (files took 17.43 seconds to load)
0 examples, 0 failures

Randomized with seed 31670
```

I'm using Rspec version 3.4.4

**UPDATE**: Just had a look at the Rspec code, and it seems it's happening because of [this line](https://github.com/rspec/rspec-core/blob/350c21b6f66a54267ff615ed16604e017122e6be/lib/rspec/core/world.rb#L137). It actually ignores `run_all_when_everything_filtered ` if the tests are being run with `--only-failures`. Why would this be?

**Comment by myronmarston** [comment]
See #1941 and #1945.  We decided that since the point of `--only-failures` is run only failures, it did not make sense to allow the option to run all passing specs instead.  It exits quickly and tells you all examples were filtered out, which allows you to re-run w/o `--only-failures` if you really want to run all specs.

You're right that it's a bit inconsistent and perhaps confusing--but it would have been more confusing, IMO, to allow a flag like `--only-failures` to be cancelled out by another config option.  This is especially true when you consider why `run_all_when_everything_filtered` exists: it was created so that you can leave focus-filtering config in place:

``` ruby
RSpec.configure do |c|
  c.filter_run :focus => true
  c.run_all_when_everything_filtered = true
end
```

Without `run_all_when_everything_filtered`, the `:focus => true` filtering would _always_ be in effect, meaning that nothing would run if nothing was focused.  Not ideal.

Anyhow, as it happens in RSpec 3.5 we're introduced a new filtering option that is meant to replace this setup (and effectively soft-deprecates `run_all_when_everything_filtered`):

``` ruby
RSpec.configure do |c|
  c.filter_run_when_matching :focus => true
end
```

This is a _conditional_ filter that only applies when something is tagged with `:focus` metadata.  The new API allows you to pick on a filter-by-filter basis which should be conditionally applied and which should be unconditionally applied -- where as `filter_run_when_matching` forced all filtering to be conditional.

See #2260 for the implementation of the new config option and #1920 for some background.  #1920 in particular goes into some of the issues that the semantics of `run_all_when_everything_filtered` cause -- which is why we are doing away with it.

We plan to remove `run_all_when_everything_filtered` in RSpec 4, FWIW.

**Comment by constantm** [comment]
Thanks for the in-depth explanation!
