### ISSUE TITLE
Intermittent undefined method `example_group_finished'

### ISSUE THREAD

**Issue by perlun** [rspec/rspec-core#2267]
This is with `rspec` 3.4.1, as can be seen in the stack trace.

I have no real idea on _why_ this is happening, unfortunately. One of my specs is causing a `stack level too deep` error; could that be what's confusing it somehow?

Suggestions are welcome, thanks for an absolutely awesome product. Can't find anything better at this price. 😄 

```
NoMethodError: undefined method `example_group_finished' for #<NoMethodError:0x6fd9dbe6>
               run at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:555
         run_specs at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115
               map at org/jruby/RubyArray.java:2414
         run_specs at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115
  with_suite_hooks at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680
         run_specs at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114
            report at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77
         run_specs at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113
               run at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89
               run at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73
            invoke at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41
            (root) at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/gems/rspec-core-3.4.1/exe/rspec:4
              load at org/jruby/RubyKernel.java:1059
            (root) at /Volumes/extra/git/ecraft/ecraft.uxfactory.server-2014.1/src/server/gems/jruby/1.9/bin/rspec:1
```

**Comment by mrageh** [comment]
Can you please create a reproduce this problem in another repo and post the link here?

**Comment by myronmarston** [comment]
That's a very strange error, @perlun.  According to your stack trace, the error is happening [on this line](https://github.com/rspec/rspec-core/blob/v3.4.1/lib/rspec/core/example_group.rb#L555):

``` ruby
reporter.example_group_finished(self)
```

What's weird is that your error indicates that `reporter` is a `NoMethodError` instance.  But I have no idea how that's possible, because `reporter` is a local variable [passed as an argument](https://github.com/rspec/rspec-core/blob/v3.4.1/lib/rspec/core/example_group.rb#L536) to the method, and on [line 538](https://github.com/rspec/rspec-core/blob/v3.4.1/lib/rspec/core/example_group.rb#L538) it apparently was able to call `reporter.example_group_started` without getting a similar error (because if it did, it never would have made it into the `begin/rescue/ensure` block).

Seems like a bug in JRuby, TBH.  Perhaps related to the stack overflow error; maybe the stack overflow is causing memory corruption resulting in this error (and hiding the underlying cause)?

Regardless, there's no way we can do anything about this without a reproducible example.  If you can come up with one (in the form of a gist or a git repo, ideally), we'll gladly dig in further.

**Comment by perlun** [comment]
Thanks for the feedback thus far. I managed to make a repro case, it was quite easy actually: https://github.com/perlun/rspec-bug

If you run it with JRuby 1.7.25, you should be able to get this error (intermittently). Sometimes it can succeed 3 times and work the fourth time.

With JRuby 9.1.1.0, I didn't manage to reproduce it (and the stack overflow exception is changed to `java.lang.StackOverflowError` there). So your notion that it seems like a bug in JRuby _seems_ plausible, but I wouldn't mind if you gave it a look anyway (I'll definitely file a JRuby bug in case we end up at that conclusion).

**Comment by JonRowe** [comment]
I'm pretty confident this is a JRuby bug caused by the stack overflow

**Comment by headius** [comment]
StackOverflow is not a safe thing to recover from on *any* implementation, because it can happen at any time, in any piece of code, including VM methods that maintain VM state.
