### ISSUE TITLE
Rspec not raising error on invalid statement

### ISSUE THREAD

**Issue by NimishaS** [rspec/rspec-core#2281]
I was facing an issue where all my specs were not running while running `rspec spec\unit` command.
I found that one of my specs had this kind of statement:
```
expect(object).to receive(:method).with(:argument).and_raise(SystemExit)
```
This spec was not returning any error, but none of the specs were running after this.

I changed this statement into:
```
expect{ object.method(argument) }.to raise_error(SystemExit)
```
All the specs ran successfully after this.

If the previous statement is incorrect, then `rspec` should throw an error

**Comment by samphippen** [comment]
Hi @NimishaS. This is intentional behaviour.

the job of `and_raise` on `receive` is to set the method call up to raise the specified error. As such, the behaviour you're seeing is correct and not surprising to me at all. See the docs here: https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/raising-an-error. `SystemExitError` is the error one throws when one wants the program to exit. This is exactly what I'd expect.

**Comment by NimishaS** [comment]
Hi @samphippen , thanks for the quick reply.

The example you shared https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/raising-an-error has `allow` statement which will raise an error and exit with a non-zero code.
While in my case, the statement was `expect`. Even if it is supposed to exit from the program, should the exit code be zero?

**Comment by samphippen** [comment]
Hi @NimishaS 

yes, `raise SystemExit` exits with zero.

**Comment by NimishaS** [comment]
Sorry as I am still curious to understand this behavior.

Why should the specs written after `expect(object).to receive(:method).with(:argument).and_raise(SystemExit)` not be executed? Please explain me the usecase where a user would like to kill  the execution of specs.

**Comment by samphippen** [comment]
`expect(object).to receive(:say).with(:ponies).and_raise(SystemExit)` sets up the `:say` method on `object` to do two things

1) expect that method is called at some point during the execution of the test
2) raise a `SystemExit` when that method is called.

It *does not* set up an expectation that that method will raise `SystemExit`. You are expecting on the call being received, not what the call does.

In Ruby, an uncaught system exit will cause the process to immediately exit (with status code zero unless the `SystemExit` is constructed with a non zero exit status). RSpec does not catch that particular exception, and so the process exits as soon as the method is called on your object.

**Comment by JonRowe** [comment]
> Why should the specs written after expect(object).to receive(:method).with(:argument).and_raise(SystemExit) not be executed?

It's important to understand that the `expect(this).to receive(...).and_*` methods are not 'I expect `this` to receive ... and it will do *' but 'I expect `this` to receive ... and then do *'. Rather than specifying what you expect the code to do you are **replacing the implementation**.

Thus you are telling Ruby you want to try to exit when `object` receives `method`.

> Please explain me the usecase where a user would like to kill the execution of specs.

This statement is valid not because a user might want to kill specs (this would be a round about way of doing that), but they might want to test their exit handling code. Maybe they want to prevent exit until clean up is called? or ask are you sure etc?
