### ISSUE TITLE
autorun doesn't work with "-e"

### ISSUE THREAD

**Issue by rdp** [rspec/rspec-core#2343]
At least in my env :|

```

$ jruby ./overlayer.spec.rb -e "reload the JSON"
...
LoadError: no such file to load -- /Users/packrd/dev/ruby/sensible-cinema/spec/the

```
(and exit)

**Comment by myronmarston** [comment]
Autorun does not support RSpec's command line switches.  I don't think we can.

The problem is that the executable you are running is `jruby`, not `rspec`, and `jruby` has its own option parsing.  If you run `jruby --help` you'll see that it supports a `-e` switch:

```
-e 'command'    one line of script. Several -e's allowed. Omit [programfile]
```

This is what is going on in your example.  I don't think there's anything we can do about this, and even if there was, I'm not convinced we should--it would be confusing for us to monkey with another command's option parsing.

One of the main benefits of the `rspec` command is to provide a rich CLI.  If you want to use that CLI, you need to use the `rspec` command instead of using autorun and invoking the spec file with `ruby` or `jruby`.

**Comment by JonRowe** [comment]
@myronmarston's comment still applies, we only support command line switches via the `rspec` command, as we can't control how they are provided to us, here it looks like jruby is ignoring your `"`s and providing the other two words as files to us.
