### ISSUE TITLE
Feature idea: rspec --continue

### ISSUE THREAD

**Issue by JakeKaad** [rspec/rspec-core#2352]
Similar to --only-failures, it would be nice to have the option to continue a test run that had been aborted early. 

This would allow me to stop the runner, check the stack trace of a failing test and then continue the test runner while I work on debugging the failing test.

**Comment by myronmarston** [comment]
Have you tried `--next-failure`?  It does almost exactly what you're talking about.

**Comment by JakeKaad** [comment]
It only works if you have run the entire test suite through once. What I am proposing is to be able to stop a fresh run and then continue it.

**Comment by myronmarston** [comment]
> It only works if you have run the entire test suite through once. What I am proposing is to be able to stop a fresh run and then continue it.

While `--next-failure` does require that you've run the suite at least once (or run the parts of the suite you are interested in just once), I don't understand why that's a problem: it seems like it would only affect you when you've cloned a project for the first time and are running the spec suite for the first time.  Wouldn't you normally want to run the entire suite when you've just cloned a project for the first time?  After you've run it at least once, there's the state for `--next-failure` to work off of.

**Comment by JakeKaad** [comment]
My QA team has a very large feature test suite that takes an hour to complete.  

If I could stop the test suite early and then restart it I can decrease the feedback time from the QA team to the development team.

**Comment by myronmarston** [comment]
As it turns out, there's not an option called `--continue`, but our CLI does support what you want!

Try this:

```
$ rspec --fail-fast --tag last_run_status:unknown
```

The failure filtering is implemented by adding `last_run_status` metadata to every example.  Examples which have no record of ever having been run have this set to `unknown`.  `--tag last_run_status:unknown` causes it to filter to just example which haven't run yet, effectively continuing from where it stopped on the last run.

Let me know if that doesn't work, but I do believe it should fit your needs.
