### ISSUE TITLE
New feature: Example groups - ability to override examples

### ISSUE THREAD

**Issue by gogiel** [rspec/rspec-core#2370]
It's not possible to override single examples included in an example group.
Testing inheritance/mixins with example groups is nearly not possible when part of the code is overridden.

Code example:
```ruby
shared_examples "test" do
  it "is true" do
    puts "True is true"
    expect(true).to eq true
  end
end

it_behaves_like "test" do
  oit "is true" do # oit mean overridden-it
    puts "False is false"
    expect(false).to eq false
  end
end
```

This code prints `False is false`. If you swap `oit` with `it` both `True is true` and `False is false` is printed out.

Implementation example: https://github.com/rspec/rspec-core/compare/master...4ormat:override-example?expand=1

**Comment by myronmarston** [comment]
Examples aren't methods and I don't think the same concept of method overrides applies.  If an example in the shared group shouldn't apply to all uses of the group, then maybe it shouldn't be in the shared group.  Or you can accept options to optionally include it:

``` ruby
shared_examples "test" do |skip_is_true: false|
  unless skip_is_true do
    it "is true" do
      puts "True is true"
      expect(true).to eq true
    end
  end
end

it_behaves_like "test", skip_is_true: true do
  it "is true" do
    puts "False is false"
    expect(false).to eq false
  end
end
```

Or you might consider making the example rely upon helper methods provided by the host group so that it can be written in a way that is universally true for all host groups.

Regardless, I don't think it makes sense for us to take on the complexity of `oit` given there are other ways to achieve this, so I'm going to close this.
