### ISSUE TITLE
config option to specify profile threshold

### ISSUE THREAD

**Issue by betesh** [rspec/rspec-core#2378]
I propose a config option that could be used to limit how many slow examples / example groups are displayed:

    rspec --profile 10 --slow-example 0.05 --slow-example-group 0.1

This would mean "List all examples slower than 0.05 seconds, up to a maximum of 10 examples, and list example groups slower than 0.1 seconds, up to a maximum of 10 example groups"

This is not the same as being able to specify the number of slow examples / example groups.  This is about defining what's considered slow.  I still want to see a maximum of 10, but sometimes I want to see less.

**Use case:**

All my test are reasonably fast except for 2 example groups.  I don't want to turn off profiling because I want to pay attention to the slow ones.  In the mean time, however, the profile output is mostly noise.

    Top 10 slowest example groups:
    Test 1
     10.2057 seconds average (10.2057 seconds / 1 example) ./spec/my_spec.rb:10
    Test 2 
     5.11493 seconds average (1.70498 seconds / 3 examples) ./spec/my_spec.rb:20
    Test 3
     0.09761 seconds average (0.09761 seconds / 1 example) ./spec/my_spec.rb:50

**Questions**
Before I start working on a PR, I'd like some feedback:

1. Would a PR be accepted?
2. Are the option names reasonable?
3. What would be appropriate default values?  Zero (i.e. always show all 10)?

**Comment by myronmarston** [comment]
> Would a PR be accepted?

Probably not at this point.  RSpec is so feature-ful that we have a pretty high bar for inclusion of new features at this point.  I'd encourage you to build this as an extension, and then if it gets lots of usage and love in the community, we can consider adding it (or something like it) to RSpec in the future.

> Are the option names reasonable?

I think it would be better (both in an extension, and if this got added to RSpec) to use the `RSpec.configure` block for this instead of a CLI option.  We intentionally limit the CLI options so `rspec --help` isn't a huge wall of text, and we also usually only expose CLI options for things that users are likely to want to frequently change for individual runs (such as filtering, picking a different formatter, etc).  This seems like a project-level setting that you'd want to set once and leave in place, so I think `RSpec.configure` is better:

``` ruby
RSpec.configure do |c|
  c.slow_example_threshold = 0.05
  c.slow_group_threshold = 0.1
end
```

> What would be appropriate default values? Zero (i.e. always show all 10)?

If we were to add this, I'd want a default of `0` so that the option is effectively ignored if the user does not set it (even though the implementation would always check it).

Anyhow, if you do want to add this as an extension, you could do something like this:

``` ruby
RSpec.configure do |c|
  c.add_setting :slow_example_threshold, default: 0
  c.add_setting :slow_group_threshold, default: 0
end

require 'delegate'

class FilteredProfileNotification < SimpleDelegator
  def slowest_examples
    slowest_examples = super()
    # TODO: filter them before returning them using RSpec.configuration.slow_example_threshold
  end

  def slowest_groups
    slowest_groups = super()
    # TODO: filter them before returning them using RSpec.configuration.slow_group_threshold
  end
end

module ProfileFormatterOverrides
  def dump_profile(profile_notification)
    super(FilteredProfileNotification.new(profile_notification))
  end
end

require 'rspec/core/formatters/profile_formatter'
RSpec::Core::Formatters::ProfileFormatter.prepend ProfileFormatterOverrides
```

Good luck!

**Comment by xaviershay** [comment]
Agree with @myronmarston. I'd probably take this for a spin if you did build as an extension though.

**Comment by betesh** [comment]
Thanks @myronmarston.  A configuration option is definitely the way to go.  And I appreciate that you basically did the heavy lifting for me.

**Comment by betesh** [comment]
Here's my implementation:

    RSpec.configure do |c|
      c.add_setting :slow_example_threshold, default: 0
      c.add_setting :slow_group_threshold, default: 0
    end

    require 'delegate'

    class FilteredProfileNotification < SimpleDelegator
      def slowest_examples
        @slowest_examples ||= super().select do |example|
          example.execution_result.run_time >= RSpec.configuration.slow_example_threshold
        end
      end

      def slowest_groups
        @slowest_groups ||= super().select do |description, example|
          example.fetch(:average) >= RSpec.configuration.slow_group_threshold
        end
      end
    end

    module ProfileFormatterOverrides
      def dump_profile(profile_notification)
        super(FilteredProfileNotification.new(profile_notification))
      end
    end

    require 'rspec/core/formatters/profile_formatter'
    RSpec::Core::Formatters::ProfileFormatter.prepend ProfileFormatterOverrides
