### ISSUE TITLE
Failing date comparison makes BigDecimal comparisons fail

### ISSUE THREAD

**Issue by hard2hack** [rspec/rspec-core#2383]
Hello, I've run into this problem while refactoring some specs, consolidating multiple expectations on an object into one expectation with `have_attributes`.
In short: if one of the attributes is a timestamp (not matching) and another attribute is a BigDecimal (matching) the error includes the BigDecimal field as well

The scenario is something like this: 
- ActiveRecord model `SomeModel`
- timestamp field `date` (postgres: `timestamp without time zone`)
- BigDecimal field `value` (postgres: `numeric(5,4)`)

this is the failing spec
```
it 'replicates the behaviour' do
  date_1 = Time.now.change(usec: 111)
  date_2 = Time.now.change(usec: 222)
  value = BigDecimal.new(5, 4)
  model = SomeModel.new(date: date_1, value: value)
  expect(model).to have_attributes(date: date_2, value: value)
end
```
this is an extract of the failing message
```
expected #<SomeModel ...> to have attributes 
{:date => 2017-02-02 21:48:50.000222000 +0000, :value => 5.0 (#<BigDecimal:9f5ad80,'0.5E1',9(27)>)} 
but had attributes 
{:date => 2017-02-02 21:48:50.000111000 +0000, :value => 5.0 (#<BigDecimal:9d9ce30,'0.5E1',9(18)>)}
       Diff:
       @@ -1,3 +1,3 @@
       -:date => 2017-02-02 21:48:50.000222000 +0000,
       -:value => 5.0 (#<BigDecimal:9f5ad80,'0.5E1',9(27)>),
       +:date => 2017-02-02 21:48:50.000111000 +0000,
       +:value => 5.0 (#<BigDecimal:9d9ce30,'0.5E1',9(18)>),
```
you can see that the error reports the `value` field in the non-matching attributes as well, in addition the BigDecimal format is mistakenly represented `9(27)` instead of `9(18)`

if the `date` field is corrected then the spec passes
```
it 'replicates the behaviour' do
  date = Time.now
  value = BigDecimal.new(5, 4)
  model = SomeModel.new(date: date, value: value)
  expect(model).to have_attributes(date: date, value: value)
end
```

I'm running 
```
ruby 2.3.3
rspec 3.5.0
```

Please let me know if you need further informations

**Comment by myronmarston** [comment]
This is unfortunate but expected behavior, given the trade-offs we chose to make with our differ.

The failure message (e.g. "expected SomeModel to have attributes ... but had attributes") does _not_ filter the displayed attributes to just the unmatched attributes.  It includes the actual and expected values for all keys passed to `have_attributes`.  So the fact that the decimal is listed there does _not_ mean that RSpec thinks the decimals do not match.

Our diffs are purely textual diffs provided by [diff-lcs](https://github.com/halostatue/diff-lcs).  That means, the diff lines are based entirely on difference in textual output when inspecting the expected and actual values.  Since decimals include an object id in their `inspect` output, two decimals that are equal according to `==` will still show up in the diff.  IMO, this is a problem that should be solved with `BigDecimal`.  Since BigDecimal objects are immutable numeric values, where the object id does not come into play in any of its operations, I think it's inappropriate for Ruby to include the object ID in the `inspect` output -- similarly to how integers and floats just print the number and not their object id.

Since we don't use a pure object differ (which does not depend upon a textual diffs) we can wind up with mis-leading diff output.  But it's useful often enough that we still include it.

Does that make sense?

P.S. In the future please report bugs related to expectations to the [rspec-expectations issue tracker](https://github.com/rspec/rspec-expectations/issues).
