### ISSUE TITLE
Stdlib time methods are not loaded

### ISSUE THREAD

**Issue by GCorbel** [rspec/rspec-core#2428]
Hi,

I'm working on a project with RSpec 3.6 and I have a lot of undefined methods with Time. It seems than all methods [here](https://ruby-doc.org/stdlib-2.1.1/libdoc/time/rdoc/Time.html#method-c-parse) are not defined.

I tried to change the executable of rspec like this : 

```
require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../../../../app/Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"
load Gem.bin_path("rspec-core", "rspec")
require 'time'
Time.parse('12')
```

It fail but this : 

```
require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../../../../app/Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"
require 'time'
load Gem.bin_path("rspec-core", "rspec")
Time.parse('12')
```

it works.

It works with spring probably because it requires time.

Is it a bug ?

**Comment by myronmarston** [comment]
RSpec users are responsible for loading the libraries they use, whether in the standard library or in the form of a gem. The standard way we recommend doing that is to require libraries that you use at the top of files that use them. It ensures they are loaded where needed and documents what a file's dependencies are.

**Comment by GCorbel** [comment]
I totally agree but requiring the library after doesn't work. It do not add
the stdlib methods.

**Comment by myronmarston** [comment]
In general, it works to require time from a file while running `rspec`.  For example, consider this spec file:

``` ruby
# spec/time_spec.rb
require 'time' if ENV['REQUIRE_TIME']

RSpec.describe Time do
  it 'can parse a time' do
    expect(Time.parse('2017-05-29T12:30:00Z').year).to eq 2017
  end
end
```

Running it without the environment variable fails:

```
$ rspec spec/time_spec.rb
F

Failures:

  1) Time can parse a time
     Failure/Error: expect(Time.parse('2017-05-29T12:30:00Z').year).to eq 2017

     NoMethodError:
       undefined method `parse' for Time:Class
     # ./spec/time_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.00209 seconds (files took 0.08484 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/time_spec.rb:4 # Time can parse a time
```

...but running it with the environment variable succeeds:

```
$ REQUIRE_TIME=1 rspec spec/time_spec.rb
.

Finished in 0.00386 seconds (files took 0.08627 seconds to load)
1 example, 0 failures
```

So there must be something different about your environment.  A few ideas:

* Are there any other files named `time` on your `$LOAD_PATH`?  If so, `require 'time'` could require them instead of stdlib `time`.  Note that RSpec puts both `lib` and `spec` on your load path, so if you have `lib/time.rb` or `spec/time.rb` in your project, that could happen.
* Are you putting the require at the top of files that use `Time` or just editing the executable file like you showed above?  I wouldn't expect `require 'time'` after `load Gem.bin_path("rspec-core", "rspec")` to work, because when the rspec executable is loaded, it immediately starts loading and running your specs....and then when all that is done, the `load` call returns, and you load `time`, long after it was needed.

If you can't figure out the problem, you'll need to share an executable example so one of us can take a look, as there's no way for us to guess what is unique about your environment.

**Comment by GCorbel** [comment]
You're right. There was a file I was not aware of in `lib/time.rb`. It's in conflict with the standard time class for an unknown reason but if I remove it, it works.

I will find a solution, thanks !
