### ISSUE TITLE
Let helper method is not being updated when in a block

### ISSUE THREAD

**Issue by RoyLee** [rspec/rspec-core#2432]
Hi, I am using a block to test various cases but the `let` variable in each `it` test example is never updated. In the following example, `x` is always `"c"` for each example but it should be updated to the value in variable x. Is this by design?

```
describe "Test" do
  context "when a test " do
    ["a","b","c"].each do |x|
      let(:test_var) {x}
      it "should modify the let variable" do
        expect(test_var).to eql x
      end
    end
  end
end
```
(running version 3.4.4)
Thanks!

**Comment by myronmarston** [comment]
Yes, it is by design.  `let` defines a method in the `context`, and anytime you redefine a method, the last definition wins.

In your example, you have access to `x` in the scope of the example, anyway, so why do you even need to define a `let`?  If you do want to define one, you can do:

``` ruby
describe "Test" do
  ["a","b","c"].each do |x|
    context "when a test (#{x})" do
      let(:test_var) {x}
      it "should modify the let variable" do
        expect(test_var).to eql x
      end
    end
  end
end
```

By making each element in your array generate its own context, it ensures the `let` declarations do not stomp each other.  It also ensures that each test gets a unique description.
