### ISSUE TITLE
rspec strange behavior when use different binary.

### ISSUE THREAD

**Issue by zw963** [rspec/rspec-core#2439]
Following is some reproduce in my linux:

Following is the rspec wrapper create by Rubygems.
```sh
─ 19:15  zw963 ⮀ ~/Project/simple_cacher ⮀ ⭠ (2b2969b) master ➦ ruby-2.3.4@simple_cacher
 ╰─ $ 1  which rspec |head -n1
/home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/bin/rspec
```

Use this binary to run rspec, it not worked. (This is somewhat expected behavior, because
rspec no where to know `./lib` is in current `$LOAD_PATH`

```rb
 ╭─ 19:15  zw963 ⮀ ~/Project/simple_cacher ⮀ ⭠ (2b2969b) master ➦ ruby-2.3.4@simple_cacher
 ╰─ $ /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/bin/rspec

An error occurred while loading ./spec/simple_cacher_spec.rb.
Failure/Error: class SimpleCacher

TypeError:
  SimpleCacher is not a class
# ./lib/simple_cacher.rb:3:in `<top (required)>'
# ./spec/simple_cacher_spec.rb:1:in `require'
# ./spec/simple_cacher_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00019 seconds (files took 0.05512 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

But when I run rspec-core binary directly ... it worked now ... weird.

```sh
 ╭─ 19:15  zw963 ⮀ ~/Project/simple_cacher ⮀ ⭠ (2b2969b) master ➦ ruby-2.3.4@simple_cacher
 ╰─ $ 1  ~/.rvm/gems/ruby-2.3.4@simple_cacher/gems/rspec-core-3.6.0/exe/rspec
....waiting 3 seconds
.waiting 3 seconds
.

Finished in 6.02 seconds (files took 0.09301 seconds to load)
6 examples, 0 failures
```

This failed gem is [here](https://github.com/zw963/simple_cacher), Thanks

**Comment by zw963** [comment]
I add new commit to fixed with ``require_relative``, ``2b2969b`` is this example entry.

**Comment by xaviershay** [comment]
Run `rspec --version` to see if you're getting the same one?

**Comment by zw963** [comment]
@xaviershay 

```sh
$ /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/bin/rspec --version
RSpec 3.6
  - rspec-core 3.6.0
  - rspec-expectations 3.6.0
  - rspec-mocks 3.6.0
  - rspec-support 3.6.0

$ /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/bin/rspec

An error occurred while loading ./spec/simple_cacher_spec.rb.
Failure/Error: class SimpleCacher

TypeError:
  SimpleCacher is not a class
# ./lib/simple_cacher.rb:3:in `<top (required)>'
# ./spec/simple_cacher_spec.rb:1:in `require'
# ./spec/simple_cacher_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00019 seconds (files took 0.05545 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

 $ 127  /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/gems/rspec-core-3.6.0/exe/rspec --version
RSpec 3.6
  - rspec-core 3.6.0
  - rspec-expectations 3.6.0
  - rspec-mocks 3.6.0
  - rspec-support 3.6.0

$ /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/gems/rspec-core-3.6.0/exe/rspec
....waiting 3 seconds
.waiting 3 seconds
.

Finished in 6.02 seconds (files took 0.0933 seconds to load)
6 examples, 0 failures

**Comment by zw963** [comment]
Following is two files content:

```rb
 ╰─ $ cat /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/bin/rspec
#!/usr/bin/env ruby_executable_hooks
#
# This file was generated by RubyGems.
#
# The application 'rspec-core' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rspec-core', 'rspec', version)
else
gem "rspec-core", version
load Gem.bin_path("rspec-core", "rspec", version)
end
```

```rb
 ╰─ $ cat /home/zw963/.rvm/gems/ruby-2.3.4@simple_cacher/gems/rspec-core-3.6.0/exe/rspec
#!/usr/bin/env ruby

require 'rspec/core'
RSpec::Core::Runner.invoke
```

IMO, my locally have many gems share used by many project, those gem just drop into $LOAD_PATH,
all gems work perfect well for me, it this case, I never use Rubygems generated ``wrapper binary``, I don't
know those technology use, maybe binary $PATH? anyway, not use them(even not manager by gem), work perfect well.

**Comment by myronmarston** [comment]
I think I figured out the problem.  Before your change in https://github.com/zw963/simple_cacher/commit/1714f0b31e8c67c90f49cf217c0afbb52002e78f, your `lib/simple_cacher/version.rb` file defined `SimpleCacher` as a _module_, not a class.  But in `lib/simple_cacher.rb` it defines it as a class.  These are mutually exclusive definitions; a constant cannot be both a class and a module.  The error you were getting ("SimpleCacher is not a class") indicates that it had already loaded your `version` file and `SimpleCacher` had been defined as a module; then when you loaded `simple_cacher.rb`, it tried to redefined it as a class and Ruby raised an error.  It looks like the only place your `version` file is loaded is from your gemspec:

https://github.com/zw963/simple_cacher/blob/2b2969b60bdffb90d626bec5d7c226420dc5d587/simple_cacher.gemspec#L4

It's normal to load it from your gemspec (`bundle gem` generates that for you) but you should also load it from the top of your `simple_cacher.rb` file (via `require 'simple_cacher/version'`) so that the `SimpleCacher::VERSION` constant is available to users of your gem.  Since the version file was not being loaded from `simple_cacher.rb`, it meant that the `SimpleCacher` constant mis-match did not always occur--it only occurred when something loaded your gemspec.  I believe that the Rubygems wrapper loads your gemspec as part of looking for the right gem to load, and as a result, you got the error when running `rspec` via the wrapper, but did not get the error otherwise.

Here's my advice:

* Add a `require 'simple_cacher/version'` to the top of your `simple_cacher.rb` file so that the version file always gets loaded.  This will ensure the `SimpleCacher::VERSION` constant is defined for your users and that the behavior of your library is more consistent.
* Change the `require_relative '../lib/simple_cacher'` back to `require 'simple_cacher'`--you shouldn't need `require_relative` there as the change from `module SimpleCacher` to `class SimpleCacher` was the real fix.
* If you have any copies of old releases of `simple_cacher` installed locally, uninstall them to ensure that Rubygems does not load an old gemspec that wrongly defines the `SimpleCacher` as a module.

**Comment by zw963** [comment]
@myronmarston , really good catch!! 

I had change my gem as your's perfect advice, thanks very much.

**Comment by zw963** [comment]
@myronmarston , 

BTW, I like this new default behavior which auto add current gem `lib/` into `$LOAD_PATH`,
though use  `minitest + rails` for a long time, always those `sweet point` make me back to 
rspec after a while or use with a gem.
