### ISSUE TITLE
Surprising behavior when both include and exclude are applied to same spec

### ISSUE THREAD

**Issue by georgeu2000** [rspec/rspec-core#2441]
Use case: I use a Guardfile that does not run JS specs because they are slow and intrusive:

    guard :rspec, cmd:'bundle exec rspec --tag ~js', all_on_start:true do

In `spec_helper`:

```
RSpec.configure do |config|
  config.filter_run_including focus: true
  config.run_all_when_everything_filtered = true
  ...
```

During development, I focus a single spec:

     describe 'Foo', :js, :focus do
      ...

Now, it will not run in guard because tag `exclude` appears to trump `focus`.

Is this expected or desired behavior? It is counterintuitive to me because when I focus a spec it should always run. 

If this behavior can be updated, I will be happy to do PR.

**Comment by georgeu2000** [comment]
Here's a work-around which is OK, but I wonder if anyone else is surprised by existing behavior.

`Guardfile`

    guard :rspec, cmd:'SUPPRESS_JS_SPECS=true bundle exec rspec', all_on_start:true do


`spec_helper`

```
RSpec.configure do |config|
  config.filter_run_including focus: true
  config.filter_run_excluding js: true if ENV[ 'SUPPRESS_JS_SPECS' ]
```

**Comment by myronmarston** [comment]
I can see why this is surprising, but there are other situations where doing what you're asking would be surprising.  For example:

``` ruby
# spec_helper.rb
RSpec.configure do |config|
  config.filter_run_excluding :jruby unless RUBY_PLATFORM == 'java'
  config.filter_run_including focus: true
  config.run_all_when_everything_filtered = true
end
```

``` ruby
# foo_spec.rb

RSpec.describe Foo, :focus => true do
  it "foos" do
    # ...
  end

  it "bars" do
    # ...
  end

  it "foos in a unique way on JRuby", :jruby do
    # ...
  end
end
```

Here we've got 3 focused specs, of which one is tagged with `:jruby`, and, as long as we are running on MRI, the `:jruby` spec has been configured to be excluded.  The current filtering logic gives precedence to exclusions over inclusions.  That makes it work correctly for situations like this (where an exclusion filter is being used to exclude certain specs that should never run in a certain environment), but makes it confusing for a case like yours.

Unfortunately, there's no way for RSpec to guess which filter should take precedence in cases like this.  We decided a long time ago to give exclusions precedence (since they are often used to filter based on ruby version, OS, ruby interpretter, etc).  Changing which has precedence now would be a breaking change.  Your best option is the environment variable approach you've using, I think.

**Comment by georgeu2000** [comment]
OK, thank you for the explanation.
