### ISSUE TITLE
Wrapper (helper) methods and Failure/Error message

### ISSUE THREAD

**Issue by asterite** [rspec/rspec-core#2461]
Hi!

I'll explain the motivation for the issue first and then a possible solution, if this is really a problem of interest.

In one of our projects in my company we'd like to use RSpec, but we'd like to be able to write:

```ruby
assert_equal y, x
```

instead of

```ruby
expect(x).should eq(y)
```

Now, we could use `expect_with :minitest` except that then we lose the really nice diff output. We'd also like to use the `expect` syntax for other cases (like `be`, `include`, etc.).

In short, we can probably do this:

```ruby
def assert_equal(x, y)
  expect(y).to eq(x)
end
```

That works, but the problem is that now the "Failure/Error" message part gives less useful information. For example:

```ruby
require "rspec"

def assert_equal(a, b)
  expect(b).to eq(a)
end

describe "foo" do
  it "bar" do
    assert_equal 2, 1
  end
end
```

We get:

```
  1) foo bar
     Failure/Error: expect(b).to eq(a)
     
       expected: 2
            got: 1
     
       (compared using ==)
     # ./foo_spec.rb:4:in `assert_equal'
     # ./foo_spec.rb:9:in `block (2 levels) in <top (required)>'
```

The "Failure/Error" part says `expect(b).to eq(a)`, and it will always say that, and that's not very helpful.

If we had used `expect(1).to eq(2)` we would have seen exactly that in the "Failure/Error" message.

I figured that maybe RSpec has something to remove that `assert_equal` method from the backtrace. And in fact there is! We can do:

```ruby
RSpec.configure do |config|
  config.backtrace_exclusion_patterns += [/assert_equal/]
end
```

But that only removes `assert_equal` from the backtrace:

```ruby
  1) foo bar
     Failure/Error: expect(b).to eq(a)
     
       expected: 2
            got: 1
     
       (compared using ==)
     # ./foo_spec.rb:13:in `block (2 levels) in <top (required)>'
```

We still get `expect(b).to eq(a)` in the output. Ideally I'd like to see `assert_equal 2, 1` in the "Failure/Error" part.

It seems `ExceptionPresenter` is the class responsible for determining what that "Failure/Error" should be. But it's not taking the backtrace exclusion patters into account.

With this diff:

```diff
diff --git a/lib/rspec/core/formatters/exception_presenter.rb b/lib/rspec/core/formatters/exception_presenter.rb
index f35aaffe..deb3dae0 100644
--- a/lib/rspec/core/formatters/exception_presenter.rb
+++ b/lib/rspec/core/formatters/exception_presenter.rb
@@ -231,6 +231,8 @@ module RSpec
 
           exception_backtrace.find do |line|
             next unless (line_path = line[/(.+?):(\d+)(|:\d+)/, 1])
+            next if RSpec.configuration.backtrace_formatter.exclude?(line)
+
             path = File.expand_path(line_path)
             loaded_spec_files.include?(path) || path =~ line_regex
           end || exception_backtrace.first
```

we now get this output:

```
  1) foo bar
     Failure/Error: assert_equal 2, 1
     
       expected: 2
            got: 1
     
       (compared using ==)
     # ./foo_spec.rb:13:in `block (2 levels) in <top (required)>'
```

I believe this is a much better output, and that using the backtrace filters in this case to improve the "Failure/Error" message makes sense.

Thoughts?

**Comment by myronmarston** [comment]
Great question!

Your idea won't actually work; in particular, this code isn't correct:

``` ruby
RSpec.configure do |config|
  config.backtrace_exclusion_patterns += [/assert_equal/]
end
```

The patterns are _filename_ patterns, not _method name_ patterns, so this code would exclude lines of code coming from files containing `assert_equal`.

And as it happens, RSpec already has a way to deal with this, you just have to use a different config option :).  When extracting a code snippet to display, RSpec looks for code in what it considers to be the project's source code.  You can configure what it considers to be in the project's source code via the `config.project_source_dirs` option.  Here's a way you can use it to achieve what you're looking for.

First, create `spec/hidden_source/assertions.rb` with these contents:

``` ruby
module Assertions
  def assert_equal(a, b)
    expect(b).to eq(a)
  end
end

RSpec.configure do |config|
  config.include Assertions
end
```

When this file is loaded, it'll add the `assert_equal` method so you can use it anywhere.  I've put it in a directory named `hidden_support` so that we can specifically exclude this directory from what RSpec considers to be project source code.  Then, in `spec/spec_helper.rb`, add the following lines:

``` ruby
# require the file we created above so it's always loaded
require 'hidden_support/assertions'

# remove `spec` from the list of dirs RSpec considers to be part of the project source...
config.project_source_dirs.delete("spec")

# ...and add back file and directory directly under `spec` except the `hidden_support` subdir
(Dir.entries(File.expand_path("..", __FILE__)) - [".", "..", "hidden_support"]).each do |entry|
  config.project_source_dirs << "spec/#{entry}"
end
```

With this config in place, any code in `spec/hidden_support` will not be considered when RSpec is trying to extract a code snippet to display--instead it'll show the caller's code (e.g. `assert_equal 1, 2`).

Let me know if that doesn't work for you!

**Comment by asterite** [comment]
That did work, thank you!

As a note, my solution, which now I understand wasn't good, **did** work, but only because the backtrace in Ruby includes the method name, like in:

```
"/foo/test_rspec/foo_spec.rb:32:in `assert_equal'"
```

so it was mostly working by coincidence.

**Comment by myronmarston** [comment]
> As a note, my solution, which now I understand wasn't good, did work, but only because the backtrace in Ruby includes the method name, like in:

You're right, I didn't think about that :).
