### ISSUE TITLE
Can I do not run other examples if specific one didnt pass ?

### ISSUE THREAD

**Issue by Nondv** [rspec/rspec-core#2477]
Hello!
Sorry, I wasnt be able to google it properly.

Let's say I have this group:

```ruby
it { should be_a Array }
it { should include :something }
it { should include :another }
```

Can I prevent rspec from running examples 2 and 3 if first one is failed?
Yes, I know that I can join them in one `it`, but still.

Sorry for my english

**Comment by myronmarston** [comment]
You can use `--fail-fast` to have RSpec abort as soon as one example fails.  That said, for this specific case, you can really express that with a single expectation:

``` ruby
it "returns an array with :something and :another" do
  expect(subject).to be_an(Array).and include(:something, :another)
end
```

In general, I tend not to use the one-liner syntax.  In this kind of situation it leads to slower specs (as you are performing the same setup 3 times instead of only 1 time).  If you have "dependent" expectations--where later expectations should only be checked if the an earlier one passes--then they really all belong in the same example.
