### ISSUE TITLE
Create an example group dynamically from within configuration.

### ISSUE THREAD

**Issue by pedroadame** [rspec/rspec-core#2480]
Hi,

Having
```
RSpec.shared_examples "shared" do
  it "executes this shared example" do
    expect(true).to be true
  end
end
```
Is there a way to inject it as `it_behaves_like` in every, for example, described model class from a `before` hook?

Wanted approach:
```
RSpec.configure do |conf|
  conf.before(:all, type: :model) do |group|
    group.include_examples "shared"
  end
end
```
Or something similar.
I wish to inject it on the example groups but it is not allowed from an example or construct scope.

**Comment by myronmarston** [comment]
Since an example group contains both examples and contextual things like `before` hooks and `let` declarations, a shared example group can be used to either share examples or share the context.  Ultimately, `include_examples` and `include_context` do the exact same thing, but are named to provide the emphasis of what the shared group is being used for.

With that background out of the way, this should do what you want:

``` ruby
RSpec.configure do |conf|
  conf.include_context "shared", type: :model
end
```

While it's called `include_context` instead of `include_examples`, it will include the examples defined in your shared group since they do the same thing, as I mentioned above.

**Comment by pedroadame** [comment]
Is there any way to check described class in this hook (for example passing a `Proc`) for conditionally include_context in some models and not in some others?

**Comment by myronmarston** [comment]
> Is there any way to check described class in this hook (for example passing a Proc) for conditionally include_context in some models and not in some others?

Yep, you can pass a proc or lambda:

``` ruby
RSpec.configure do |conf|
  conf.include_context "shared", type: lambda { |type, other_meta|
    type == :model && other_meta[:described_class] == Blah
  }
end
```

That said, I would recommend taking a different approach:

``` ruby
RSpec.configure do |c|
  c.define_derived_metadata(type: :model) do |meta|
    meta[:include_shared_model_specs] = true if meta[:described_class] == Blah
  end

  c.include_context "shared", include_shared_model_specs: true
end
```

The nice thing about this is it lets you auto-tag all the groups that you want to with this bit of metadata, and then use it in multiple different ways.  One way you can use it is to include the shared example group automatically, but you can also use it to things like filter to just those specs (e.g. `rspec --tag include_shared_model_specs`).
