### ISSUE TITLE
--only-failures is ignored when passing file names with line numbers. 

### ISSUE THREAD

**Issue by robotdana** [rspec/rspec-core#2526]
if spec/a_spec.rb is passing:
```
rspec --only-failures spec/a_spec.rb:5 spec/a_spec.rb:10 spec/b_spec.rb:5 spec/b_spec.rb:10
```
will run `spec/a_spec.rb:5` and `:10` anyway, yet
```
rspec --only-failures spec/a_spec.rb spec/b_spec.rb
```
will only run spec/b_spec.rb (as I'd expect)

(this is also the case for --next-failure)

Checked that it's an issue on 3.6.0, 3.7.2, master

**Comment by JonRowe** [comment]
This is due to how RSpecs filtering works, `--only-failures` is a shortcut for adding an inclusion filter for `:last_run_status` of `'failed'`, when you add in line numbers you are adding specific filters for those files too, the affect of this is a combined or filter, so this is actually behaving as expected. See #1622 and #2522 for more discussion around this.
