### ISSUE TITLE
prepend_before not working as expected

### ISSUE THREAD

**Issue by mirubiri** [rspec/rspec-core#2540]
If I understood the method correctly this should not be happening:

### Your environment
* Ruby version: 2.2.9
* rspec-core version: 3.6.0

### Steps to reproduce
```ruby
describe 'something' do
  before { puts 'this goes first}
  context 'something else' do
    prepend_before { puts 'this goes second' }
    it 'is true' do
      expect(true).to eq true
    end
  end
end
```

### Expected behavior
In console:
'this goes second'
'this goes first'

### Actual behavior
in console:
'this goes first'
'this goes second'

**Comment by JonRowe** [comment]
> \- (void) prepend_before(*args, &block)
Adds block to the front of the list of before blocks in the same scope (:example, :context, or :suite).

As per the docs, this only works in the same scope, so the other before is outside the scope that `prepend_before` can modify

**Comment by pjungwir** [comment]
This still seems like a bug to me. The "scope" in the docs refers to the optional parameter for `before`/`prepend_before`, i.e. how often the test runs (once per example/context/suite), not what block it's in. Both `before` calls above are for the `:example` scope. Interpreting "scope" as "block" takes away most of the value from `prepend_before`.

**Comment by JonRowe** [comment]
The `before` calls are in different classes as part of the heirarchy, the first is parent of the parent class and the second the the actual class.

>  Interpreting "scope" as "block" takes away most of the value from prepend_before.

It doesn't because normally you'd use it to override a `before` you've inherited in your top level class, or via an include, where you don't control the order of the `before` definition, in the example you can easily provide the correct definition.
