### ISSUE TITLE
Hi i having an error while trying to load my test

### ISSUE THREAD

**Issue by kryswebdev** [rspec/rspec-core#2547]
### Subject of the issue

<img width="1280" alt="screen shot 2018-06-26 at 13 55 16" src="https://user-images.githubusercontent.com/33628010/41913577-94d654b2-7948-11e8-857d-c949e4fa2a5e.png">

### Your environment
* Ruby version:
* rspec-core version:

**Comment by myronmarston** [comment]
As the error says, no directory or file exists at `/Users/krystlemensah/Desktop/DjGear/spec/models`.  You ran `rspec spec/models` from the `/Users/krystlemensah/Desktop/DjGear` directory, which tells RSpec to load the spec files at that path or within that directory.  Since that path does not exist on your file system, the exception you're seeing is raised by design so you get a clear error.
