### ISSUE TITLE
--exclude-pattern only works when the files to run are directories

### ISSUE THREAD

**Issue by johnwu96822** [rspec/rspec-core#2548]
### Subject of the issue
Say we have a test file: `spec/examples/example_spec.rb`. The expectation is that if I set it in `--exclude-pattern`, it should not run. It turned out that the `--exclude-pattern` only works when the files to run are directories. It does not work when the files to run are files.

#### Files to run are directories
This exclusion will work and `spec/examples/example_spec.rb` will not run:
`rspec spec/examples --exclude-pattern "spec/examples/example_spec.rb"`

#### Files to run are files
This will not work, and `spec/examples/example_spec.rb` will still run:
`rspec spec/examples/example_spec.rb --exclude-pattern "spec/examples/example_spec.rb"`

I think this is due to this:
https://github.com/rspec/rspec-core/blob/v3.7.1/lib/rspec/core/configuration.rb#L1997

Where the exclude-pattern is only applied here when the file to run is a directory:
https://github.com/rspec/rspec-core/blob/v3.7.1/lib/rspec/core/configuration.rb#L2015

The exclude-pattern is not applied when the file to run is not a directory:
https://github.com/rspec/rspec-core/blob/v3.7.1/lib/rspec/core/configuration.rb#L2049

Why would someone put a file in the pattern to run and then place it in the `--exclude-pattern` to make it not to run? One use case is the parallel_tests gem https://github.com/grosser/parallel_tests where directories of files are expanded and invoked as files on parallel `rspec` commands. In this case if `rspec` is invoked by files, it would not honor the `--exclude-pattern` option that we specify on `parallel_rspec`.

### Your environment
* Ruby version: 2.5.1
* rspec-core version: 3.7.1

**Comment by JonRowe** [comment]
I'm afraid this is by design, when you mention a file specifically you are essentially creating an inclusion filter, which take priority over exclusion filters.

Why? Your example creates a good use case here:

`rspec spec/examples/example_spec.rb --exclude-pattern "spec/examples/example_spec.rb"` 

While this is pretty non-sensical on its own, (why would you exclude the file you've specified to run?) we should consider that you could have run `rspec spec/examples/example_spec.rb` but have `--exclude-pattern "spec/examples/example_spec.rb"` in a `.rspec` or other external configuration and not know it. 

If we were to use the exclusion pattern you would see `0 examples, 0 failures` etc which would be pretty confusing, so instead we will always run files directly mentioned. (See also if you mention an example by id or line number that is always run too).

I suggest that `parallel_rspec` should either not execute specs by file by shelling to us, (you could execute RSpec programmatically which would allow you to specific the specs to run yourself, you should still be able to managing forking here, we do something similar in our own bisect tool) or if it's going to do this it should respect `--exclude-pattern` itself and not even attempt to run such specs.

**Comment by aarsilv** [comment]
The parallel test case laid out by @johnwu96822 is a good example and one I have come across leveraging CircleCI's parallelization. When one wants to parallelize but still blanket exclude tests, their CirlceCI config will have a series of commands similar to: 
```
TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
EXCLUDEFILES=**/tests/that/{we,want}/to/exclude**/*_spec.rb
bundle exec rspec $TESTFILES --exclude-pattern $EXCLUDEFILES --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
```
In this situation, we want the exclusion filter applied to the files specified inclusion filter. This is also the behavior I would expect (as opposed to ignoring the exclusion filter).

**Comment by JonRowe** [comment]
> This is also the behavior I would expect (as opposed to ignoring the exclusion filter).

It's not ignored, it's just a lower priority filter than the files you have specifically included and this behaviour is unlikely to be changed.

However you should be able to achieve your circle CI command with:
```
EXCLUDEFILES="tests/that/\(we\|want)/to/exclude/.*_spec.rb"
TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | grep -v $EXCLUDE_FILES | circleci tests split --split-by=timings)
bundle exec rspec $TESTFILES --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
```

(Note I changed the glob to a pattern for grep, but other command line tools are capable of producing a correct output without out help here).
