### ISSUE TITLE
Is rspec modifying ERB?

### ISSUE THREAD

**Issue by jcavalieri** [rspec/rspec-core#2553]
### Subject of the issue

Is rspec modifying ERB?

### Your environment
* Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
* rspec-core version: rspec-core (3.7.0)

### Steps to reproduce

I have a class that loads a yaml config file that allows for env vars to be interpolated.

E.g.

```
client1:
  token: <%= ENV['API-TOKEN-CLIENT1'] %>
```

And in the class

`YAML.safe_load(ERB.new(File.read(config)).result)`

### Expected behavior

ERB should still work. And works with when using `rails c`

### Actual behavior

ERB no longer works when using rspec

**Comment by myronmarston** [comment]
RSpec does not modify or monkey patch ERB in any way.  We do load and use ERB in order to render the `.rspec` options file (in case someone is using dynamic ERB there) but we do not interact with ERB beyond that.

When you say, "ERB no longer works when using rspec", what do you mean?  What is the change in behavior of ERB when running in an RSpec environment?  If there is an exception, what is the exception message and stack trace?  What leads you to believe RSpec is the cause of the change in behavior and not something else in your environment?  Can you provide a reproducible example that we can run to demonstrate the issue?

**Comment by jcavalieri** [comment]
Hi @myronmarston ,

ERB is not binding the the mocked env vars. That is how it is not working.

Looking into this, it looks like for some reason mocked env vars are not being bound.

`allow(ENV).to receive(:[]).with('CLIENT_1').and_return('Jibberish')`

Unfortunately the I believe the code that does the binding is in C libs. I kinda suspect that the kernel might have its own copy of the env vars from the execution start. And therefore wouldn't be looking at the modified ENV.

-John

**Comment by JonRowe** [comment]
It's common to configure env in your spec helper like so:

```Ruby
# spec_helper.rb
ENV['API-TOKEN-CLIENT1'] ||= 'Jibberish'
```

But it would be a better idea to inject env into your code, and then you can safely pass in a normal hash as a collaborator instead.

**Comment by JonRowe** [comment]
Its probably worth mentioning also, that your code is probably being executed before RSpec runs tests, if your `YAML.safe_load(ERB.new(File.read(config)).result)` is in an evaluated part of code rather than an executed part of code, it will reflect the value of `ENV` at evaluation, which will not be in the context of the mock unless you are performing the evaluation yourself.

**Comment by jcavalieri** [comment]
@JonRowe ,

You've described exactly what is happening. Thanks!

Closing.

-John
