### ISSUE TITLE
nested :if doesn't work as expected?

### ISSUE THREAD

**Issue by ioquatix** [rspec/rspec-core#2639]
```ruby
RSpec.describe "Foo", if: false do
	it "foo" do
	end
	
	context "Bar", if: true do
		it "bar" do
		end
	end
end
```

Gives the output

```
Foo
  Bar
    bar
```

I feel if the top level context is disabled, shouldn't it also skip the inner context?

**Comment by JonRowe** [comment]
As `if:` is just a special metadata name which causes an example to be skipped, the feature to consider here is metadata and how its applied. We want inner metadata to override outer metadata, so by the time example checks for `if: ` its true so the example is run and the output produced.

So I'm afraid this is working by design! Sorry!

**Comment by ioquatix** [comment]
Okay that makes sense.

I worked around it by putting tacking on an if at the end:
