### ISSUE TITLE
exclude_pattern config doesn't work

### ISSUE THREAD

**Issue by Hirurg103** [rspec/rspec-core#2671]
### Subject of the issue
I tried configure rspec to exclude a folder in the `configure` block but it doesn't work for me

### Your environment
* Ruby version: ruby 2.5.3p105
* rspec-core version: 3.9.0

### Steps to reproduce

Folder structure `tree -a .`:
.
├── .rspec
├── .ruby-version
├── Gemfile
├── Gemfile.lock
└── spec
    ├── shared
    │   └── common_spec.rb
    ├── spec_helper.rb
    └── versions_spec.rb

2 directories, 5 files

---

```
# Gemfile
source "https://rubygems.org"

gem "rspec", "3.9.0"
```

---

```
# .rspec
--format documentation
--color
```

---

```
# .ruby-version
2.5.3
```

---

```ruby
# spec/spec_helper.rb
RSpec.configure do |config|
  config.exclude_pattern = "shared/**/*_spec.rb"
end
```

---

```ruby
# spec/shared/common_spec.rb
require 'spec_helper'

describe "Common" do

  it 'should be excluded' do
    # common tests
  end

end
```

---

```ruby
# spec/versions_spec.rb
require 'spec_helper'

describe 'Versions' do
  it 'should test versions' do
    # versions test
  end
end
```

---

### Expected behavior
When I run `bundle exec rspec` I would want to see the following output

```
Versions
  should test versions

Finished in 0.00131 seconds (files took 0.1037 seconds to load)
1 example, 0 failures
```

### Actual behavior
But rspec runs specs in the shared folder for some reason although I explicitly configured to exclude that folder:

```
Common
  should be excluded

Versions
  should test versions

Finished in 0.00235 seconds (files took 0.19294 seconds to load)
2 examples, 0 failures
```

**Comment by pirj** [comment]
Thanks for reporting.

The problem here is that initially RSpec runs without configuration, and builds a list of files to run, and then the configuration is loaded from the first file being executed.

It's common and [recommended](https://relishapp.com/rspec/rspec-core/v/3-9/docs/configuration/pattern) to add `--require spec_helper` to `.rspec` file. It's also [what `rspec init` command adds](https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/project_initializer/.rspec) to `.rspec` by default.

**Comment by Hirurg103** [comment]
Thanks @pirj , you helped me

**Comment by pirj** [comment]
You're welcome!
