### ISSUE TITLE
Typo in have_received results in valid, but incorrect, matcher

### ISSUE THREAD

**Issue by rangerscience** [rspec/rspec-core#2726]
### Subject of the issue
`have_received(:foo)` returns a RSpec::Mocks::Matchers::HaveReceived
`have_recieved(:foo)` returns a RSpec::Matchers::BuiltIn::Has
Oh, typos :)

### Your environment
* Ruby version: 2.6
* rspec-core version: 3.7

### Steps to reproduce
```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.7.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.describe 'typo' do
  it 'have_received return HaveReceived object' do
    expect(have_received(:foo)).to be_a(RSpec::Mocks::Matchers::HaveReceived)
  end

  it 'have_recieved unexpectedly returns a Has object' do
    expect(have_recieved(:foo)).to be_a(RSpec::Matchers::BuiltIn::Has)
  end
end
```

### Expected behavior
Throw a "this doesn't exist, did you mean <correct spelling>" error.

### Actual behavior
Returns a working matcher... but not the expected matcher.

**Comment by JonRowe** [comment]
Hello! Sorry you ran into this, however I have closed this because while this is not the ideal situation (because of the typo) this is the expected behaviour. 

You are trying to use the `have_received` matcher from `rspec-mocks` but there is also the `have_<n>` in `rspec-expectations` matcher that checks for `<expected>.<n>?` results on your target object. So when you mistakenly use the wrong name you are getting a different matcher that has no idea about your typo, its not feasible for us to give this matcher knowledge of the other matcher and I'm hesitant to work up a list possible typos for rspec-mocks to "guard" it'd never be an exhaustive list.

Also this is the wrong repo, it has no matchers in it.

**Comment by rangerscience** [comment]
Oh interesting. Well, first question, what'd be the correct repo? Then, I'll see if I ever come up with a creative way to deal with this...

**Comment by rangerscience** [comment]
I mean - and I recognize this'd more be a question for the other repo - what if the typo was an alias for the correct method?

**Comment by JonRowe** [comment]
> Well, first question, what'd be the correct repo? 

As I mentioned above, there is rspec-mocks and rspec-expectations, they each have their own repo.

> I mean - and I recognize this'd more be a question for the other repo - what if the typo was an alias for the correct method?

Thats a slippery slope, how many typos do we add? And as its incorrect, do we emit warning? an error? What do we do the next time someone requests a typo "helper"? In general we haven't followed the approach
