### ISSUE TITLE
Allow order specs by modification time

### ISSUE THREAD

**Issue by MatheusRich** [rspec/rspec-core#2762]
### Subject of the issue

Quite often is useful to run tests that you've just modified. RSpec lets you to define custom ordering, so I have this snipped configured in my projects:

```ruby
config.register_ordering(:global) do |items|
  items.sort_by { |item| -File.mtime(item.metadata[:absolute_file_path]).to_i }
end
```

I thought it might be useful to upstream this for more users to use this with an option `--order modification_time`. Thoughts?

### Your environment
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]

RSpec 3.9
  - rspec-core 3.9.2
  - rspec-expectations 3.9.2
  - rspec-mocks 3.9.1
  - rspec-rails 4.0.1
  - rspec-support 3.9.3

**Comment by pirj** [comment]
This is interesting. However this neglects the previous ordering, be it `defined` or `random` that relates to the order of the examples inside the spec, right?
I've seen suites really depending on `defined` order, wouldn't this break it? Do you think it would be possible to add this sorting, which is really to order the spec files, a second-tier ordering?

Another idea would be only be running the recently modified specs, as reported by, say, `git`.

Doesn't `guard` achieve the same goal for you by the way?

**Comment by JonRowe** [comment]
This is an interesting feature suggestion, although its so easy to implement I'm sort of on the fence as saying it could easily be a plugin rather than a core feature.

> However this neglects the previous ordering, be it defined or random that relates to the order of the examples inside the spec, right?

Yes thats the point.

> I've seen suites really depending on defined order, wouldn't this break it? 

Yes but then they wouldn't choose this ordering scheme, its an alternative not a combination (also those suites should be fixed).

> Doesn't guard achieve the same goal for you by the way?

I see guard as orthogonal to this, it reruns files as they change, not running the whole suite by the modification times. This would allow you (combined with `--next-failure`) to find the most recent failing spec, which you might not have just changed, but could have changed say, yesterday.

Where it potentially falls down is it has no knowledge of library file changes, so it'll always be local filesystem spec mtime, and not true age, or wether its actually been covered.

**Comment by MatheusRich** [comment]
My goal was really to combine this with `--next-failure `. In my experience, modified specs are the most susceptible to failures.

**Comment by pirj** [comment]
One thing you may be interested in is https://github.com/toptal/crystalball/
It's a sophisticated tool that infers the specs that might break depending on your code changes, and one its most naïve strategies is to run the modified specs.

**Comment by MatheusRich** [comment]
So, should I open a PR for this? I'm not sure if the whole core-team agrees with the feature :smile:

**Comment by pirj** [comment]
Can you implement it as a plugin, rather than baking in into RSpec? Will you have to monkey-patch internals, or does RSpec provide you necessary interface to make such an extension, @MatheusRich ?

**Comment by MatheusRich** [comment]
To be honest, I don't know. Probably there's a plugin support. But I'm thinking if there's any value in making it a separated gem. I mean, I'm lazy, so I'd prefer to setup `guard` or `crystalball` than just add a gem for this simple thing.

**Comment by pirj** [comment]
Do you think there is something actionable here @MatheusRich or this ticket can be closed?

**Comment by MatheusRich** [comment]
I think the maintainers aprooved the feature, so I'm keen to implementing it

**Comment by JonRowe** [comment]
I don't feel strongly against it, so if @benoittgt wants to champion it I'm fine with that @pirj
