### ISSUE TITLE
Docsite is down

### ISSUE THREAD

**Issue by robert-resemble** [rspec/rspec-core#3009]
### Subject of the issue
Hi team, I am trying to reach the Docsite https://relishapp.com/rspec/rspec-core but it looks like it's 500ing 

It looks this way across every package. I don't have Heroku access so I can't really do much in terms of looking at logs / helping out :( 

![image](https://user-images.githubusercontent.com/125229616/221679332-6d19a410-2ef4-4125-a327-4dd8815c0aa9.png)

**Comment by JonRowe** [comment]
:Wave: There is an issue with [relishapp](https://relishapp.com/) at the moment, you can find our website at https://rspec.info which has our API documentation, or read the cucumber scenarios directly from this repo.

See: https://github.com/rspec/doc-site/issues/5#issuecomment-1446152910

Closing because this is not an rspec-core issue.

**Comment by JonRowe** [comment]
The relish documentation has been replaced by a self hosted version, you can find it via https://rspec.info/documentation/
