### ISSUE TITLE
Use a non-1 error exit code

### ISSUE THREAD

**Issue by cgriego** [rspec/rspec-core#444]
In a tool external to the rspec process, I'm trying to determine the difference between a Ruby exception killing the process outside of RSpec's test execution (like undefined constant) and an RSpec test failure. The easiest way to do this would be via the exit code. When Ruby exits with an exception, it exits with an exit code of 1. When an RSpec tests fails today it also exits with an exit code of 1. If RSpec used a different exit code then I could tell the difference.

**Comment by Startouf** [comment]
Hello, sorry to revive an old post, but the original request was 

> I'm trying to determine the difference between a Ruby exception killing the process outside of RSpec's test execution (like undefined constant) and an RSpec test failure

I am not sure the problem was solved by the PR. I have actually ran into a similar issue (cf [StackOverflow](https://stackoverflow.com/questions/52873453/catch-rspec-error-occured-outside-of-example)) and despite having found an alternative, I would have loved to have a different error code to distinguish more easily failures outside of Rspec

**Comment by JonRowe** [comment]
@Startouf it does because `rspec --failure-exit-code=2` will exit `1` if a ruby exception kills the whole process, whilst it will exit with `2` if RSpec manages the failure.

**Comment by JonRowe** [comment]
Additionally we also catch some failures which happen within our control, but outside of specs. You could write a formatter to catch these and exit with your own code.
