### ISSUE TITLE
should include 'invert-tests' switch

### ISSUE THREAD

**Issue by ghost** [rspec/rspec-core#598]
As best I can understand, a properly written test should ALWAYS fail when its "should" is replaced with "should_not" and vice versa.

I often interchange "should" and "should_not" to make sure my tests fail as expected.  If a test "fails to fail", I know it isn't really testing what I think it's testing -- a very important bit of information.  But this requires a lot of manual work.

It would be useful if RSpec offered an `--invert-tests` command-line switch which has the following effects:
- replaces every "should" with "should_not" and vice versa
- reports a passing test as a failure ("expected xxx to fail, but instead it passed")

(I was tempted to call this the `--null-hypothesis` switch, but that may simply be too cute.  What do you think?)

**Comment by jdehaan** [comment]
I find myself in a situation needing to double check that both the expectation is ok and the not expectation must fail, because sometimes both pass.... For whatever reason (broken test code after refactoring tests, we did not notice that because tests still pass...)

My trick is currently to patch the expectations lib (comments removed):

`rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb`

```ruby
        def _to(matcher=nil, message=nil, &block)
          prevent_operator_matchers(:to) unless matcher
          RSpec::Expectations::PositiveExpectationHandler.handle_matcher(target, matcher, message, &block)
        end

        def _not_to(matcher=nil, message=nil, &block)
          prevent_operator_matchers(:not_to) unless matcher
          RSpec::Expectations::NegativeExpectationHandler.handle_matcher(target, matcher, message, &block)
        end
        # alias not_to _not_to
        # alias to _to
        # alias to_not _not_to
        alias to _not_to
        alias not_to _to
        alias to_not _to
```

I activate either the one or other aliases. Wouldn't that do the trick in case of a global flag as well? Do I miss something? I read about a high complexity to implement the feature, I do not understand from a functional point of view why a negation of tests can be so complicated to implement... That is why I would like to get some more info and adjust my checks to solve my current problems with the test code correctly.

**Comment by jdehaan** [comment]
Sorry again I know this ticket is closed but this functionality would be really good to have. I now slowly realize that integrating it is indeed challenging at some points, once it comes to reporting something adequate for example. But inverting could be considered as "meta" testing = testing the tests and instead of aliasing define a new method that gets the result of the actual test and expects it to be a failure... I am not familiar with the code at all, I am just throwing ideas...

If there is a wish to get such a feature implemented from the community side, if I get some hints on how this could/should roughly be done, I can invest some time in digging into it. At the moment we really suffer from tests that are wrong (both the test and its negation pass) and difficult to detect in the mass.

**Comment by JonRowe** [comment]
As you've found it's relatively easy to integrate a temporary negation of assertions, the issue becomes in integrating this feature across `rspec-core` and `rspec-expectations`, and having a way for `rspec-core` to know that the inverted failure is expected, essentially recording failures as passes, etc... Is a fair amount of work for a feature that would be infrequently used... 

And then there is the point that for most, if not all of RSpec's matchers it would always pass, I can't think of any examples of our matchers that would pass in the positive and then not fail when negated...

I feel that broken test code is a different class of problem and there is no guarantee that if this feature existed it would catch it any better.

You could wrap `pending` around your examples when refactoring them, maybe with your patch as an extension module etc... expecting them to fail...

Can you provide some examples of where a matcher passes for both `to` and `not_to`? It might help me understand the specific problem you are facing.

**Comment by jdehaan** [comment]
You are fully right, the main reason for such situations is that the test code itself was too complicated and ended up in situations where no expect at all was called.
Maybe checking that at least one expect check is there should be done. I pretty much got into the code now and realized that it's far to be easy to get matchers/expectations/reporting in a good consistent shape.

Thanks for your feedback, we have a pretty big code base here maybe I can see some other possibility to improve our situation. I now can fully agree on that this is a different class of problem. Thanks for taking the time to answer, I'll check your hints as well to see if that helps me any further.

**Comment by JonRowe** [comment]
Theres a long standing suggestion to implement expectation counting, but no ones ever had time to do it, its the sort of thing that needs to happen before we can enforce that an expectation happens (currently we never know really unless theres a failure) but there are some not so easy bits to that too (mostly surrounding how you deal with complex assertions and composed matchers).

**Comment by jdehaan** [comment]
Oh dear. Still that goal sounds definitively reasonable and useful. I'll make myself a picture of it.

**Comment by pirj** [comment]
@jdehaan Are you up to come up with a PoC that would make sure that at least one expectation per example has been made, and warn in case `rspec-mocks`/`rspec-expectations` are being used primarily?
I see `it { validates_presence_of(:name) }` quite often without being noticed, and static analysis can't handle edge cases.

**Comment by jdehaan** [comment]
@pirj I read several other related tickets (with similar goals like #591, #740, #759) and need to get a good picture of what is going on.

I think the first thing in the way is that a test that checks something does not raise an exception is valid (as current state of the implementation) and changing that to forced explicit expectations is a breaking change. As of my current research one thing that could also solve the dilemma is to change the initial state of an example to be pending by default and toggle to success if there is a successful expectation (with any framework used for that) and stick to failure on the first failed expectation. But that is just one idea among many.

I thought  initially that must not be a big deal but the further you get into it the more complicated it gets. My feeling is that there is something in the design that makes  this more complicated than needed. I try to get a first clear mind on what are the design goals of rspec and how an option could make sense in an universal way. At the moment I solved my issue with a manual quirk and it's not something that makes sense in a general way because Rspec is so much more flexible and modular allowing all kinds of combinations of frameworks. I try to see if one can make things fit from the example runner perspective without touching the rest (probably at the cost of an option that changes the behaviour of the runner in a breaking way, what is not a big deal if you want/need this feature... Maybe it could be made configurable at example group level?)
