### ISSUE TITLE
rspec, by default, silently ignores files missing the _spec suffix

### ISSUE THREAD

**Issue by agraves** [rspec/rspec-core#642]
We have a medium-sized Rails application using very stock Rspec settings. We write tests, place them in the appropriate subfolder, and rely on the success or failure of the "rake" command to give a commit / branch / release the thumbs up or thumbs down.

During development, however, we tend to quickly run single files or even blocks as we TDD.

Our issue is that if you accidentally omit the "_spec" suffix on a test, it is by default silently ignored when you run "rake." We've now shipped broken code three times because a developer accidentally typed "_spcc" or "_spce" or omitted the suffix entirely.

I can see the use of having the pattern option, especially in unusual testing setups, but the default is just an annoyance and source of bugs.

I propose that the default shipping pattern be: spec/*/*.rb .  Failing that, there _really_ ought to be a warning (that can be disabled) that says "X tests did not match the pattern and were skipped."

**Comment by ruiyang** [comment]
We are using 2.14.1
It also happened to us. We have 7 test just silently ignored in ci for couple of months until someone found one test failing locally.

We have some support files under spec/support folder. To avoid such mistakes in the future, We could just override the pattern to be **/**.rb. 

The question is whether I have to move all support files out of the spec folder? or it is ok for rspec to pick them up, because there is no statement of describe in those files.

**Comment by JonRowe** [comment]
Note this is a very old issue, with a documented solution (of sorts, to use `--pattern` to override the default if desired), personally I'm strongly in favour of correctly naming your spec files in the first place.
