### ISSUE TITLE
described_module

### ISSUE THREAD

**Issue by mfilej** [rspec/rspec-core#654]
Would it make sense to add `described_module` as an alias for `described_class` for when we are testing modules?

**Comment by jjg-dressipi** [comment]
Seems an odd choice to me, if `described_class` is supposed to be part of the internals, why is it exposed?  I have personally worked on code-bases where class/module names are _long_ and `described_class` is a godsent alternative to the politics of a global name-change campaign :smile: If anyone else finds themselves in need of this feature, then an easy implementation is  simply to have 
```
def described_module
  described_class
end
```
in the configuration section of your `spec_helper.rb`.

**Comment by deepj** [comment]
@JonRowe Hello, I would like to open this issue, eventually to prepare PR for this.

I think there is a room for `described_module` to be in rspec-core. Ruby supports `module_function`. And I use it for small functions. In fact, it's similar to Elixir in my case. Better it's to show on some code. Here is one of my recent example.

```ruby
module Statistics
  module_function def mean(data)
    values.sum / BigDecimal(values.size)
  end

  module_function def variance(values)
    mean = self.mean(values)

    sum = data.inject(0) { |acc, i| acc + (i - mean)**2 }
    sum / BigDecimal(data.size - 1)
  end

  module_function def standard_deviation(values)
    Math.sqrt(variance(values))
  end
end
```

I really would like to use something like

```ruby
RSpec.describe Statistics do
  describe '.mean' do
    subject { described_module.mean([1, 2, 3]) }

    it 'returns a correct result' do
      expect(subject).to eq(BigDecimal('2'))
    end
  end
end
```

**Comment by JonRowe** [comment]
:wave: I'm hesitant to add this because we'd rather people didn't use `described_class` or constants in `describe <n>`, the reasoning being its an anti-pattern in your tests. Having the module / class in the describe means the code *must* be loaded before the spec is loaded, where as delaying the need for the module to be loaded allows much easier testing in isolation.

We'd also much rather you use `subject(:mean) { Statistics.mean([1,2,3]) }` (and thus `expect(mean)` for example) as its explicit about what is going on and not some nameless thing.

You could always add `let(:statistics) { Statistics }` if you really wanted to avoid changing the constant everywhere if you needed to change the name, but thats adding code just in case you want to rename (when editors make it easy to rename...) it's also easy to do yourself if you really must.

**Comment by mfilej** [comment]
> We'd also much rather you use `subject(:mean) { Statistics.mean([1,2,3]) }` (and thus `expect(mean)` for example) as its explicit about what is going on and not some nameless thing.

@JonRowe This is completely off-topic, so please feel free to redirect me elsewhere. Does the RSpec team officially recommend using subject to store the result of a method call on the object under test? I always assumed *subject* is meant to be the *object under test*. If this was already discussed elsewhere I'd be happy to read about it.

**Comment by JonRowe** [comment]
@mfilej The RSpec team recommend `subject(:something_appropriate)` is used to highlight the er... subject... of the context (or contexts). This is usually an object, but of course in Ruby, everything is an object, and if the object under test is returned from a method thats totally valid.

**Comment by mfilej** [comment]
> because of course in Ruby, everything is an object

Of course, that's why I said the *object under test*, i.e. the unit of code that is being tested (usually) by sending messages to it.

While the result of a method call is technically also a ruby object, in my opinion that is not what is being tested—it is just a value that helps us verify that the object under test (that received the message that produced the value) is behaving correctly.

**Comment by pirj** [comment]
@mfilej apply testing style that you consider the right one:
```ruby
# without `subject`

expect(Statistics.mean([1,2,3])).to eq(2)

# or with a helper method

def mean(*args)
  Statistic.mean(*args)
end

it { expect(mean(1, 2, 3)).to eq(2) }

# or a named subject

subject(:mean) { Statistics.mean(1, 2, 3) }
it { expect(mean).to eq(2) }
```

It depends on how you structure the examples, if you reuse the same subject, or different examples/groups make expectations on different subjects.

**Comment by JonRowe** [comment]
The point of `subject(:name) { ... }` is to draw attention to the fact the result under test is extracted to what is essentially a `let`. This is one of the reasons we recommend always naming it. I would never really expect someone to do `a_subject_name.some_method`.

**Comment by marcandre** [comment]
@JonRowe wrote:
> 👋 I'm hesitant to add this because we'd rather people didn't use `described_class` or constants in `describe <n>`, the reasoning being its an anti-pattern in your tests. 

If I understand correctly, you mean that:

```ruby
# constant form (bad anti-pattern)
RSpec.describe MyGem::MyClass do
# string form (good)
RSpec.describe 'MyGem::MyClass' do
```

If so, I'd like to voice my disagreement. I personally like the first (constant) form much better.

> Having the module / class in the describe means the code _must_ be loaded before the spec is loaded, where as delaying the need for the module to be loaded allows much easier testing in isolation.

I've not had issues with this and believe that it is not a concern in the vast majority of cases.

Reasons I believe this is a common experience include:

`rspec-rails` generators create some specs with string versions, and others as constant versions. The most used ones (i.e. `model_spec`, `controller_spec`, `helper_spec`) *all use the constant form*.

`rspec-core`'s own test suite has more than *60 examples of the first (constant) form* and I could only find 4 examples of the "string" format (`'RSpec::Core::Set', 'RSpec::Core::Profiler', "::RSpec::Core::ExampleGroup", "Bisect"`).

I didn't go through all the documentation, but `ExampleGroup` has *only examples of the first (constant) form*.

A bit tangential, but I'll mention that `rubocop-rspec` has a cop that enforces, within a `describe MyClass` group, that either `MyClass` or `described_class` is always used. It's default is to *enforce the use of `described_class`*.

I hope that helps you reconsider your view on the constant form in `describe` and add `described_module` without hesitation. Let me know if I should open a new issue.

**Comment by JonRowe** [comment]
> I hope that helps you reconsider your view on the constant form in describe and add described_module without hesitation. Let me know if I should open a new issue.

It does not.

**Comment by JonRowe** [comment]
Sorry that was a bit terse, pre coffee 😂 , allow me to elaborate.

> If I understand correctly, you mean that:
> ```
> # constant form (bad anti-pattern)
> RSpec.describe MyGem::MyClass do
> # string form (good)
> RSpec.describe 'MyGem::MyClass' do
> ```
> If so, I'd like to voice my disagreement. I personally like the first (constant) form much better.

You understand correctly, I respectfully register your differing personal opinion but that doesn't change my opinion.

> > Having the module / class in the describe means the code must be loaded before the spec is loaded, where as delaying the need for the module to be loaded allows much easier testing in isolation.
>
> I've not had issues with this and believe that it is not a concern in the vast majority of cases.

Using the constant means its impossible to delay booting rails for example, until you see if you actually need to boot rails. We came to this opinion when working on PORO style Rails apps, if you follow the Rails way it's less of a problem because you are always writing integration level tests and need to have booted Rails anyway.

> rspec-rails generators create some specs with string versions, and others as constant versions. The most used ones (i.e. model_spec, controller_spec, helper_spec) all use the constant form.

The generators are a bit neglected and so they haven't been updated, most of the RSpec team in recent years have either not used `rspec-rails` in their day job, or don't use generators.

> rspec-core's own test suite has more than 60 examples of the first (constant) form and I could only find 4 examples of the "string" format ('RSpec::Core::Set', 'RSpec::Core::Profiler', "::RSpec::Core::ExampleGroup", "Bisect").

You'll note those are some of the more modern code, since forming this opinion we haven't gone back and stringified all of the older modules because of the churn that would cause, as we don't have any expensive code to load its not something we have an issue with.

> A bit tangential, but I'll mention that rubocop-rspec has a cop that enforces, within a describe MyClass group, that either MyClass or described_class is always used. It's default is to enforce the use of described_class.

A lot of rubocops opinions differ from ours, we have to configure it to meet our own test suite needs. No advice was sought from us for their defaults.

**Comment by marcandre** [comment]
Thank you for the (second 😅) reply. It might help me and others understand if there was a real-life example (gem or app) where using strings makes a positive difference we could refer to. Do you happen to have such an example?

**Comment by pirj** [comment]
I've collected some arguments pro and contra here https://github.com/rubocop-hq/rspec-style-guide/issues/104
The feedback is controversial, so unless we have some brilliant new idea we should probably not touch anything related to `described_class`.

**Comment by JonRowe** [comment]
> Do you happen to have such an example?

Consider a spec suite for a Rails app containing various specs:

```
# spec/models/user_spec.rb
require "rails_helper"
RSpec.describe User, type: :model do
end

# spec/service/service_spec.rb
RSpec.describe Service, type: :service do
end
```

With constants, like this, running `rspec --tag type:service` requires booting Rails, as it requires having knowledge of `User` which is not a trivially requirable on its own, due to the nature of Rails.

The alternative is something like this:

```
# spec/models/user_spec.rb
RSpec.describe "User", type: :model do
  before(:all) do
    require "rails_helper"
  end
end

# spec/service/service_spec.rb
RSpec.describe "Service", type: :service do
  before(:all) do
    require "lib/service/service.rb"
  end
end
```

Now when running `rspec --tag type:service` only the service code is loaded, and no Rails need be unnecessarily loaded and booted.
