### ISSUE TITLE
cannot have tag filters on shared examples

### ISSUE THREAD

**Issue by deepak** [rspec/rspec-core#692]
cannot have tag filters on shared examples.

``` ruby
describe Foo do
  it_behaves_like "something", :derp do
    puts "== [1] calling shared example"
    let(:foo) { Foo.new }
  end
end
```

In the above example we cannot filter by tag 'derp'

Full code at https://gist.github.com/3792621

Seems to me that "it" and "it_behaves_like" are similar and both should be filterable
But did not find any such mention in the docs so this seem like a feature request

**Comment by paulbhartzog** [comment]
Want to mention that this works, but I haven't seen it in any documentation:

```ruby
RSpec.shared_examples "a zog test shared" do
    context "some context" do
      it "says string matches", :zog => true do
        expect("this string").to include("this")
      end
    end
  end

  describe 'zog test' do
    it_behaves_like "a zog test shared"
  end
```

When you run `rspec test spec --format documentation --tag zog` you get the full output **_as if_** the tag were on the original test:

```
  zog test
    behaves like a zog test shared
      some context
        says string matches
```

It looks like the parser is smart enough to backtrack and produce the correct output.

If this is in any documentation please reference it here, thx. :-)

**Comment by myronmarston** [comment]
@paulbhartzog: there's no documentation for that because we've never thought of it as something worth being called out.  Maybe I don't have the mindset of a user here (since I maintain RSpec) but it's one of those "of course it works" things.  There are a ton of other things that work in shared example groups (e.g. `expect`, mocking, `let`, `subject`, nested groups, most any other RSpec feature...) that we don't call out in the docs.  It's not clear to me what is different about tagging that would make a user expect it to not work and would warrant us documenting it to correct that misconception.

**Comment by paulbhartzog** [comment]
> @paulbhartzog: there's no documentation for that because we've never thought of it as something worth being called out. Maybe I don't have the mindset of a user here (since I maintain RSpec) but it's one of those "of course it works" things. There are a ton of other things that work in shared example groups (e.g. expect, mocking, let, subject, nested groups, most any other RSpec feature...) that we don't call out in the docs. It's not clear to me what is different about tagging that would make a user expect it to not work and would warrant us documenting it to correct that misconception.

My point was that if you look at the output, it is not necessarily obvious where the line `behaves like a zog test shared` comes from, since that section of the code is **_not tagged_**. As a user I was suprised  that by tagging inside `shared_examples` I was able to get the output from the calling item.  There are several reasons ranging from newbie learning curve to counter-intuitive (or non-obvious) feature, but I just wanted to share here the fact that it **_does_** work (because RSpec is great!) :-)

**Comment by myronmarston** [comment]
We document that `it_behaves_like` generates a nested group here:

https://relishapp.com/rspec/rspec-core/v/3-5/docs/example-groups/shared-examples

The `behaves like a zog test shared` output is simply the description of the nested group generated by `it_behaves_like`.  That said, that feature of RSpec is orthogonal to the tag filtering you are commenting on and they don't interact.  It's the equivalent of this:

``` ruby
describe 'zog test' do
  context 'behaves like a zog test shared' do
    context 'some context' do
      it "says string matches", :zog => true do
        expect("this string").to include("this")
      end
    end
  end
end
```

This would produce the same output, but the `:zog` tag is not connected to the `behaves like a zog test shared` context, other than being on a nested example.  The `behaves like a zog tes shared` string would be included in the output because it is the description of the grandparent group of the example selected via `--tag zog`, and the doc output prints all the description strings of all parent groups of the selected examples.

**Comment by paulbhartzog** [comment]
> the doc output prints all the description strings of all parent groups of the selected examples.

👍
